"""
Curated culinary glossary for Cambodian Khmer food and cooking terminology.
Ensures natural, culturally accurate translations for dish names, ingredients,
cooking actions, preparation notes, categories, and post-processing corrections.
"""

# Common Cambodian dishes with culturally standard Khmer names
DISH_NAMES: dict[str, str] = {
    "fish amok": "អាម៉ុកត្រី",
    "amok trey": "អាម៉ុកត្រី",
    "amok": "អាម៉ុក",
    "bai sach chrouk": "បាយសាច់ជ្រូក",
    "pork and rice": "បាយសាច់ជ្រូក",
    "beef lok lak": "ឡុកឡាក់សាច់គោ",
    "lok lak": "ឡុកឡាក់",
    "loc lac": "ឡុកឡាក់",
    "samlor machu": "សម្លម្ជូរ",
    "samlor machu kroeung": "សម្លម្ជូរគ្រឿង",
    "samlor machu trey": "សម្លម្ជូរត្រី",
    "samlor korko": "សម្លកកូរ",
    "nom banh chok": "នំបញ្ចុក",
    "kuy teav": "គុយទាវ",
    "kuyteav": "គុយទាវ",
    "a-ping": "អាពីង",
    "aping": "អាពីង",
    "pleah sach ko": "ភ្លាសាច់គោ",
    "plea sach ko": "ភ្លាសាច់គោ",
    "bok lahong": "បុកល្ហុង",
    "cha kdao": "ឆាក្តៅ",
    "chhar knye": "ឆាខ្ញី",
    "sach ko ang": "សាច់គោអាំង",
    "kari sach moan": "ការីសាច់មាន់",
    "amok trey — fish amok steamed in banana leaf": "អាម៉ុកត្រី",
    "amok trey - fish amok steamed in banana leaf": "អាម៉ុកត្រី",
}

# Standard categories in NhamHealth
CATEGORIES: dict[str, str] = {
    "breakfast": "អាហារពេលព្រឹក",
    "lunch": "អាហារពេលថ្ងៃត្រង់",
    "dinner": "អាហារពេលល្ងាច",
    "snack": "អាហារសម្រន់",
    "snacks": "អាហារសម្រន់",
    "dessert": "បង្អែម",
    "desserts": "បង្អែម",
    "soup": "សម្ល",
    "soups": "សម្ល",
    "appetizer": "ម្ហូបកូរ",
    "appetizers": "ម្ហូបកូរ",
    "beverage": "ភេសជ្ជៈ",
    "beverages": "ភេសជ្ជៈ",
    "other": "ផ្សេងៗ",
    "grill": "ម្ហូបអាំង",
    "curry": "ការី",
    "stir-fry": "ម្ហូបឆា",
    "salad": "ញាំ / ភ្លា",
    "grills & street food": "ម្ហូបអាំង និងអាហារតាមផ្លូវ",
    "amok, curries & stir-fries": "អាម៉ុក ការី និងម្ហូបឆា",
}

# Natural culinary translations for ingredients
INGREDIENTS: dict[str, str] = {
    # Poultry / Meat / Seafood
    "chicken breast": "សាច់ទ្រូងមាន់",
    "chicken breasts": "សាច់ទ្រូងមាន់",
    "chicken thighs": "សាច់ភ្លៅមាន់",
    "chicken thigh": "សាច់ភ្លៅមាន់",
    "chicken wings": "ស្លាបមាន់",
    "chicken wing": "ស្លាបមាន់",
    "chicken drumsticks": "ជើងមាន់",
    "chicken": "សាច់មាន់",
    "pork shoulder": "សាច់ស្មាជ្រូក",
    "pork belly": "សាច់ជ្រូកបីជាន់",
    "pork loin": "សាច់ផាត់ជ្រូក",
    "pork ribs": "ឆ្អឹងជំនីជ្រូក",
    "minced pork": "សាច់ជ្រូកចិញ្ច្រាំ",
    "ground pork": "សាច់ជ្រូកចិញ្ច្រាំ",
    "pork": "សាច់ជ្រូក",
    "beef tenderloin": "សាច់គោផាត់ទន់",
    "beef sirloin": "សាច់គោជាប់ខ្លាញ់",
    "ground beef": "សាច់គោចិញ្ច្រាំ",
    "minced beef": "សាច់គោចិញ្ច្រាំ",
    "beef": "សាច់គោ",
    "fish fillet": "សាច់ត្រី",
    "fish fillets": "សាច់ត្រី",
    "freshwater fish": "ត្រីទឹកសាប",
    "catfish": "ត្រីអណ្តែង",
    "snakehead fish": "ត្រីរស់",
    "fish": "ត្រី",
    "shrimp": "បង្គា",
    "shrimps": "បង្គា",
    "prawns": "បង្គា",
    "prawn": "បង្គា",
    "squid": "មឹក",
    "crab": "ក្តាម",
    "edible tarantulas": "អាពីង",
    "tarantulas": "អាពីង",
    "tarantula": "អាពីង",
    "egg": "ស៊ុត",
    "eggs": "ស៊ុត",
    "duck egg": "ពងទា",
    "duck eggs": "ពងទា",

    # Aromatics & Herbs
    "garlic": "ខ្ទឹមស",
    "garlic clove": "កំពិសខ្ទឹមស",
    "garlic cloves": "កំពិសខ្ទឹមស",
    "cloves garlic": "កំពិសខ្ទឹមស",
    "clove garlic": "កំពិសខ្ទឹមស",
    "shallot": "ខ្ទឹមក្រហម",
    "shallots": "ខ្ទឹមក្រហម",
    "onion": "ខ្ទឹមបារាំង",
    "onions": "ខ្ទឹមបារាំង",
    "red onion": "ខ្ទឹមក្រហម",
    "spring onion": "ស្លឹកខ្ទឹម",
    "spring onions": "ស្លឹកខ្ទឹម",
    "scallion": "ស្លឹកខ្ទឹម",
    "scallions": "ស្លឹកខ្ទឹម",
    "green onion": "ស្លឹកខ្ទឹម",
    "green onions": "ស្លឹកខ្ទឹម",
    "ginger": "ខ្ញី",
    "galangal": "រំដេង",
    "turmeric": "រមៀត",
    "fresh turmeric": "រមៀតស្រស់",
    "lemongrass": "គល់ស្លឹកគ្រៃ",
    "lemongrass stalks": "គល់ស្លឹកគ្រៃ",
    "kaffir lime leaves": "ស្លឹកក្រូចសើច",
    "kaffir lime leaf": "ស្លឹកក្រូចសើច",
    "lime leaves": "ស្លឹកក្រូចសើច",
    "holy basil": "ជីរម្រះព្រៅ",
    "thai basil": "ជីរនាងវង",
    "basil": "ជីរនាងវង",
    "mint": "ជីរអង្កាម",
    "mint leaves": "ស្លឹកជីរអង្កាម",
    "coriander": "ជីរវ៉ាន់ស៊ុយ",
    "cilantro": "ជីរវ៉ាន់ស៊ុយ",
    "culantro": "ជីររណា",
    "sawtooth coriander": "ជីររណា",
    "banana leaf": "ស្លឹកចេក",
    "banana leaves": "ស្លឹកចេក",

    # Condiments & Seasonings
    "fish sauce": "ទឹកត្រី",
    "soy sauce": "ទឹកស៊ីអ៊ីវ",
    "light soy sauce": "ទឹកស៊ីអ៊ីវថ្លា",
    "dark soy sauce": "ទឹកស៊ីអ៊ីវខាប់",
    "oyster sauce": "ប្រេងខ្យង",
    "shrimp paste": "កាពិ",
    "prahok": "ប្រហុក",
    "fermented fish paste": "ប្រហុក",
    "coconut milk": "ខ្ទិះដូង",
    "coconut cream": "ក្បាលខ្ទិះដូង",
    "coconut water": "ទឹកដូង",
    "palm sugar": "ស្ករត្នោត",
    "brown sugar": "ស្ករត្នោត",
    "sugar": "ស្ករស",
    "white sugar": "ស្ករស",
    "salt": "អំបិល",
    "sea salt": "អំបិលសមុទ្រ",
    "msg": "ប៊ីចេង",
    "msg or a pinch of stock powder": "ប៊ីចេង ឬម្សៅស៊ុបបន្តិច",
    "stock powder": "ម្សៅស៊ុប",
    "chicken powder": "ម្សៅស៊ុបមាន់",
    "chicken bouillon": "ម្សៅស៊ុបមាន់",
    "bouillon powder": "ម្សៅស៊ុប",
    "black pepper": "ម្រេចខ្មៅ",
    "ground black pepper": "ម្រេចខ្មៅម៉ត់",
    "kampot pepper": "ម្រេចកំពត",
    "pepper": "ម្រេច",
    "white pepper": "ម្រេចស",
    "chili": "ម្ទេស",
    "chilies": "ម្ទេស",
    "chilli": "ម្ទេស",
    "chillies": "ម្ទេស",
    "red chili": "ម្ទេសក្រហម",
    "bird's eye chili": "ម្ទេសអាចម៍សត្វ",
    "chili flakes": "ម្ទេសម៉ត់គ្រើម",
    "chili paste": "ម្ទេសឆា",
    "tamarind": "អំពិលទុំ",
    "tamarind paste": "ទឹកអំពិលទុំ",
    "lime juice": "ទឹកក្រូចឆ្មា",
    "lime": "ក្រូចឆ្មា",
    "limes": "ក្រូចឆ្មា",
    "lemon": "ក្រូចឆ្មា",
    "tuk meric": "ទឹកម្រេចក្រូចឆ្មា",
    "tuk meric — salt, pepper and lime dip": "ទឹកម្រេចក្រូចឆ្មា",

    # Pastes & Blends
    "kroeung": "គ្រឿង",
    "curry paste": "គ្រឿងការី",
    "amok paste": "គ្រឿងអាម៉ុក",
    "yellow kroeung": "គ្រឿងលឿង",
    "red kroeung": "គ្រឿងក្រហម",
    "green kroeung": "គ្រឿងបៃតង",

    # Oils & Liquids
    "neutral oil": "ប្រេងឆា",
    "cooking oil": "ប្រេងឆា",
    "vegetable oil": "ប្រេងបន្លែ",
    "sesame oil": "ប្រេងល្ង",
    "water": "ទឹក",
    "warm water": "ទឹកក្តៅឧណ្ហៗ",
    "boiling water": "ទឹកពុះ",

    # Produce & Vegetables
    "carrot": "ការ៉ុត",
    "carrots": "ការ៉ុត",
    "cucumber": "ត្រសក់",
    "cucumbers": "ត្រសក់",
    "tomato": "ប៉េងប៉ោះ",
    "tomatoes": "ប៉េងប៉ោះ",
    "long beans": "សណ្តែកកួរ",
    "yardlong beans": "សណ្តែកកួរ",
    "green beans": "សណ្តែកកួរ",
    "morning glory": "ត្រកួន",
    "water spinach": "ត្រកួន",
    "green papaya": "ល្ហុងខ្ចី",
    "papaya": "ល្ហុង",
    "eggplant": "ត្រប់",
    "round eggplant": "ត្រប់ស្រួយ",
    "pea eggplant": "ត្រប់ពុតលំញង",
    "bean sprouts": "សណ្តែកបណ្តុះ",
    "cabbage": "ស្ពៃក្តោប",
    "bok choy": "ស្ពៃតឿ",
    "mushrooms": "ផ្សិត",
    "mushroom": "ផ្សិត",
    "peanuts": "សណ្តែកដី",
    "roasted peanuts": "សណ្តែកដីលីង",

    # Grains & Staples
    "jasmine rice": "អង្ករផ្កាម្លិះ",
    "rice": "អង្ករ",
    "cooked rice": "បាយ",
    "sticky rice": "អង្ករដំណើប",
    "glutinous rice": "អង្ករដំណើប",
    "rice noodles": "នំបញ្ចុក",
    "glass noodles": "មីសួរ",
    "tapioca flour": "ម្សៅមី",
    "rice flour": "ម្សៅអង្ករ",
    "cornstarch": "ម្សៅពោត",
}

# Natural culinary preparation notes
PREPARATION_NOTES: dict[str, str] = {
    "chop finely": "ហាន់ឲ្យម៉ត់",
    "finely chopped": "ហាន់ឲ្យម៉ត់",
    "chopped": "ហាន់",
    "cut into pieces": "កាត់ជាបំណែក",
    "cut into bite-sized pieces": "កាត់ជាដុំល្មមញ៉ាំ",
    "sliced thin": "ហាន់ជាបន្ទះស្តើងៗ",
    "thinly sliced": "ហាន់ជាបន្ទះស្តើងៗ",
    "sliced": "ហាន់ជាបន្ទះ",
    "minced": "ចិញ្ច្រាំឲ្យម៉ត់",
    "finely minced": "ចិញ្ច្រាំឲ្យម៉ត់ល្អ",
    "pounded": "បុកឲ្យម៉ត់",
    "crushed": "បុកឲ្យម៉ត់",
    "bruised": "ដំឲ្យទក់",
    "peeled": "បកសំបក",
    "peeled and deveined": "បកសំបក និងដកខ្សែខ្នងចេញ",
    "julienned": "ហាន់ជាសរសៃ",
    "shredded": "ហាន់ជាសរសៃស្តើង",
    "grated": "កោសឲ្យម៉ត់",
    "diced": "កាត់ជាដុំបួនជ្រុង",
    "washed": "លាងទឹកឲ្យស្អាត",
    "cleaned": "លាងសម្អាត",
    "drained": "ស្រង់ឲ្យស្រស់ទឹក",
    "soaked": "ត្រាំទឹក",
    "to serve": "សម្រាប់ទទួលទាន",
    "for garnish": "សម្រាប់តុបតែង",
    "for frying": "សម្រាប់ចៀន",
    "to taste": "តាមចំណូលចិត្ត",
    "plus more to serve": "និងបន្ថែមសម្រាប់ទទួលទាន",
    "hard-boiled and peeled": "ស្ងោរឲ្យឆ្អិន រួចបកសំបក",
    "soft-boiled": "ស្ងោរជ័រព្នៅ",
}

# Culinary action words for instruction translation
COOKING_ACTIONS: dict[str, str] = {
    "steam": "ចំហុយ",
    "boil": "ស្ងោរ",
    "fry": "ចៀន",
    "pan-fry": "ចៀន",
    "deep-fry": "បំពង",
    "deep fry": "បំពង",
    "grill": "អាំង",
    "barbecue": "អាំង",
    "stir-fry": "ឆា",
    "stir fry": "ឆា",
    "simmer": "រម្ងាស់",
    "stew": "ខ",
    "braise": "ខ",
    "bake": "ដុត",
    "roast": "អាំង",
    "mix well": "លាយឲ្យសព្វ",
    "mix thoroughly": "លាយឲ្យសព្វល្អ",
    "mix": "លាយ",
    "marinate": "ប្រឡាក់",
    "toss": "ច្របល់",
    "whisk": "វាយឲ្យសព្វ",
    "heat the oil": "ដាក់ប្រេងឲ្យក្តៅ",
    "bring to a boil": "ដាំឲ្យពុះ",
    "reduce heat": "បន្ថយភ្លើង",
    "cook until tender": "រម្ងាស់រហូតដល់ទន់",
    "cook until fragrant": "ឆារហូតដល់ឈ្ងុយ",
    "drain": "ស្រង់ឲ្យស្រស់ទឹក",
    "serve hot": "ទទួលទាននៅពេលក្តៅៗ",
    "serve warm": "ទទួលទាននៅពេលក្តៅឧណ្ហៗ",
    "serve": "ទទួលទាន",
}

# Post-processing fixes for machine-translated awkward culinary phrasing
POST_TRANSLATION_FIXES: list[tuple[str, str]] = [
    # Literal "steam" (noun = water vapor) -> cooking verb "steam"
    ("ចំហាយទឹក", "ចំហុយ"),
    ("ចំហាយ​ទឹក", "ចំហុយ"),
    # Literal "breast" -> chicken breast
    ("សុដន់មាន់", "សាច់ទ្រូងមាន់"),
    ("សុដន់​មាន់", "សាច់ទ្រូងមាន់"),
    ("ទ្រូងមាន់", "សាច់ទ្រូងមាន់"),
    # Awkward "mix well"
    ("លាយបានល្អ", "លាយឲ្យសព្វ"),
    ("លាយ​បាន​ល្អ", "លាយឲ្យសព្វ"),
    ("លាយល្អ", "លាយឲ្យសព្វ"),
    # Awkward "chop finely"
    ("កាត់យ៉ាងល្អ", "ហាន់ឲ្យម៉ត់"),
    ("កាត់​យ៉ាង​ល្អ", "ហាន់ឲ្យម៉ត់"),
    ("ច្របាច់ឱ្យម៉ត់", "ហាន់ឲ្យម៉ត់"),
    # Awkward "fish fillet"
    ("fillet ត្រី", "សាច់ត្រី"),
    ("សាច់ត្រី fillet", "សាច់ត្រី"),
    # Awkward curry paste
    ("curry paste", "គ្រឿងការី"),
    ("ទឹក​ម្ទេស​", "គ្រឿងការី"),
    ("ទឹកម្ទេស", "គ្រឿងការី"),
]

# Standard cooking units to preserve untouched
STANDARD_UNITS: set[str] = {
    "g", "kg", "ml", "l", "tbsp", "tsp", "cup", "cups", "clove", "cloves",
    "piece", "pieces", "stalk", "stalks", "slice", "slices", "can", "cans",
    "pinch", "pinches", "sprig", "sprigs", "bunch", "bunches"
}

