create table public.user_profile_reports (
    profile_report_id integer generated by default as identity,
    reported_user_id integer not null,
    reported_by_user_id integer not null,
    report_reason_id integer not null,
    status varchar(20) not null,
    created_at timestamp(6) not null,
    primary key (profile_report_id),
    constraint fk_profile_reports_reported_user
        foreign key (reported_user_id) references public.users (user_id),
    constraint fk_profile_reports_reporter
        foreign key (reported_by_user_id) references public.users (user_id),
    constraint fk_profile_reports_reason
        foreign key (report_reason_id) references public.report_reasons (report_reason_id)
);

create index idx_profile_reports_status_created
    on public.user_profile_reports (status, created_at desc);
