create table public.daily_nutrition_source_logs (
    nutrition_source_log_id integer generated by default as identity primary key,
    user_id integer not null,
    log_date date not null,
    source_type varchar(30) not null,
    source_id varchar(100) not null,
    calories numeric(38, 2) not null default 0,
    protein numeric(38, 2) not null default 0,
    carbs numeric(38, 2) not null default 0,
    fat numeric(38, 2) not null default 0,
    water numeric(38, 2) not null default 0,
    fiber numeric(38, 2) not null default 0,
    sugar numeric(38, 2) not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_nutrition_source_logs_user
        foreign key (user_id) references public.users (user_id) on delete cascade,
    constraint uk_nutrition_source_logs_source
        unique (user_id, source_type, source_id),
    constraint ck_nutrition_source_logs_type
        check (source_type in ('MEAL_PLAN', 'AI_SCAN'))
);

create index idx_nutrition_source_logs_user_date
    on public.daily_nutrition_source_logs (user_id, log_date);
