-- Community recipes are the author-owned source data. They can be published
-- to Community immediately; only an AI-approved recipe can be promoted to a
-- catalog meal. This flow intentionally has no chat, human-review, or
-- direct-friend-sharing tables.

CREATE TABLE recipes (
    recipe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_user_id INT NOT NULL REFERENCES users(user_id),
    recipe_name VARCHAR(150) NOT NULL,
    description TEXT,
    main_image_url TEXT,
    cooking_time_minutes INT,
    servings INT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_recipes_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_recipes_cooking_time CHECK (cooking_time_minutes IS NULL OR cooking_time_minutes > 0),
    CONSTRAINT ck_recipes_servings CHECK (servings IS NULL OR servings > 0)
);

CREATE INDEX idx_recipes_author_user_id ON recipes(author_user_id);
CREATE INDEX idx_recipes_status_updated_at ON recipes(status, updated_at DESC);

CREATE TABLE recipe_ingredients (
    recipe_ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INT NOT NULL REFERENCES recipes(recipe_id) ON DELETE CASCADE,
    ingredient_name VARCHAR(150) NOT NULL,
    amount NUMERIC(10, 2),
    unit VARCHAR(30),
    preparation_note VARCHAR(150),
    display_order INT NOT NULL,
    CONSTRAINT ck_recipe_ingredients_amount CHECK (amount IS NULL OR amount > 0),
    CONSTRAINT ck_recipe_ingredients_display_order CHECK (display_order >= 0)
);

CREATE INDEX idx_recipe_ingredients_recipe_order ON recipe_ingredients(recipe_id, display_order);

-- recipe_steps was previously used only by admin meals. Retain those rows and
-- let the same table hold a community recipe's ordered cooking steps.
ALTER TABLE recipe_steps ADD COLUMN recipe_id INT;
ALTER TABLE recipe_steps ALTER COLUMN meal_id DROP NOT NULL;
ALTER TABLE recipe_steps
    ADD CONSTRAINT fk_recipe_steps_recipe
    FOREIGN KEY (recipe_id) REFERENCES recipes(recipe_id) ON DELETE CASCADE;
ALTER TABLE recipe_steps
    ADD CONSTRAINT ck_recipe_steps_single_parent
    CHECK (num_nonnulls(meal_id, recipe_id) = 1);

CREATE INDEX idx_recipe_steps_recipe_id ON recipe_steps(recipe_id);
CREATE INDEX idx_recipe_steps_recipe_order ON recipe_steps(recipe_id, step_number);

CREATE TABLE recipe_tags (
    recipe_tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INT NOT NULL REFERENCES recipes(recipe_id) ON DELETE CASCADE,
    tag_id INT NOT NULL REFERENCES tag_types(tag_id),
    CONSTRAINT uk_recipe_tags_recipe_tag UNIQUE (recipe_id, tag_id)
);

CREATE INDEX idx_recipe_tags_tag_id ON recipe_tags(tag_id);

CREATE TABLE ai_recipe_reviews (
    ai_recipe_review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INT NOT NULL REFERENCES recipes(recipe_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    summary VARCHAR(1000),
    feedback TEXT,
    model_name VARCHAR(100),
    model_response TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_ai_recipe_reviews_status CHECK (status IN ('APPROVED', 'INCOMPLETE', 'NOT_SUITABLE'))
);

CREATE INDEX idx_ai_recipe_reviews_recipe_created ON ai_recipe_reviews(recipe_id, created_at DESC);
CREATE INDEX idx_ai_recipe_reviews_status ON ai_recipe_reviews(status);

CREATE TABLE saved_recipes (
    saved_recipe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    recipe_id INT NOT NULL REFERENCES recipes(recipe_id) ON DELETE CASCADE,
    saved_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_saved_recipes_user_recipe UNIQUE (user_id, recipe_id)
);

CREATE INDEX idx_saved_recipes_recipe_id ON saved_recipes(recipe_id);

CREATE TABLE user_recipe_ai_checks (
    user_recipe_ai_check_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    recipe_id INT NOT NULL REFERENCES recipes(recipe_id) ON DELETE CASCADE,
    ai_recipe_review_id INT REFERENCES ai_recipe_reviews(ai_recipe_review_id) ON DELETE SET NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_user_recipe_ai_checks_status CHECK (status IN ('APPROVED', 'INCOMPLETE', 'NOT_SUITABLE'))
);

CREATE INDEX idx_user_recipe_ai_checks_user_created ON user_recipe_ai_checks(user_id, created_at DESC);
CREATE INDEX idx_user_recipe_ai_checks_recipe_created ON user_recipe_ai_checks(recipe_id, created_at DESC);

-- One recipe owns one community post. Generic legacy posts remain valid with
-- a NULL recipe_id.
ALTER TABLE posts ADD COLUMN recipe_id INT;
ALTER TABLE posts
    ADD CONSTRAINT fk_posts_recipe
    FOREIGN KEY (recipe_id) REFERENCES recipes(recipe_id) ON DELETE SET NULL;
CREATE UNIQUE INDEX uk_posts_recipe_id ON posts(recipe_id) WHERE recipe_id IS NOT NULL;

-- Existing catalog meals are ADMIN/ADMIN. A COMMUNITY/AI meal has exactly one
-- source recipe and represents its AI-approved promotion into Meals.
ALTER TABLE meals ADD COLUMN source_recipe_id INT;
ALTER TABLE meals ADD COLUMN source_type VARCHAR(20) NOT NULL DEFAULT 'ADMIN';
ALTER TABLE meals ADD COLUMN approval_source VARCHAR(20) NOT NULL DEFAULT 'ADMIN';
ALTER TABLE meals
    ADD CONSTRAINT fk_meals_source_recipe
    FOREIGN KEY (source_recipe_id) REFERENCES recipes(recipe_id) ON DELETE RESTRICT;
ALTER TABLE meals
    ADD CONSTRAINT ck_meals_source_type CHECK (source_type IN ('ADMIN', 'COMMUNITY'));
ALTER TABLE meals
    ADD CONSTRAINT ck_meals_approval_source CHECK (approval_source IN ('ADMIN', 'AI'));
ALTER TABLE meals
    ADD CONSTRAINT ck_meals_recipe_promotion CHECK (
        (source_type = 'ADMIN' AND approval_source = 'ADMIN' AND source_recipe_id IS NULL)
        OR (source_type = 'COMMUNITY' AND approval_source = 'AI' AND source_recipe_id IS NOT NULL)
    );
CREATE UNIQUE INDEX uk_meals_source_recipe_id ON meals(source_recipe_id) WHERE source_recipe_id IS NOT NULL;
