-- Planner nutrition quality and explainable-personalization foundation.
-- Clinical/dietary classifications inferred from text are intentionally marked
-- PENDING_REVIEW and must not be presented as medical advice.
alter table
    public.planner_meals
add
    column if not exists fiber_grams numeric(10, 2),
add
    column if not exists sugar_grams numeric(10, 2),
add
    column if not exists sodium_mg numeric(10, 2),
add
    column if not exists saturated_fat_grams numeric(10, 2),
add
    column if not exists serving_size numeric(10, 2),
add
    column if not exists serving_unit varchar(30),
add
    column if not exists nutrition_data_quality varchar(20) not null default 'UNVERIFIED',
add
    column if not exists nutrition_source varchar(255);

do $ $ begin if not exists (
    select
        1
    from
        pg_constraint
    where
        conname = 'ck_planner_meals_extended_nutrition'
) then
alter table
    public.planner_meals
add
    constraint ck_planner_meals_extended_nutrition check (
        (
            fiber_grams is null
            or fiber_grams >= 0
        )
        and (
            sugar_grams is null
            or sugar_grams >= 0
        )
        and (
            sodium_mg is null
            or sodium_mg >= 0
        )
        and (
            saturated_fat_grams is null
            or saturated_fat_grams >= 0
        )
        and (
            serving_size is null
            or serving_size > 0
        )
    );

end if;

if not exists (
    select
        1
    from
        pg_constraint
    where
        conname = 'ck_planner_meals_nutrition_quality'
) then
alter table
    public.planner_meals
add
    constraint ck_planner_meals_nutrition_quality check (
        nutrition_data_quality in ('UNVERIFIED', 'ESTIMATED', 'VERIFIED')
    );

end if;

end $ $;

create table if not exists public.diet_types (
    diet_type_id integer generated by default as identity primary key,
    code varchar(40) not null unique,
    name_en varchar(100) not null,
    name_km varchar(150),
    description_en text,
    is_active boolean not null default true,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp
);

create table if not exists public.planner_meal_diet_types (
    planner_meal_id integer not null references public.planner_meals(planner_meal_id) on delete cascade,
    diet_type_id integer not null references public.diet_types(diet_type_id) on delete cascade,
    classification_source varchar(20) not null default 'MANUAL',
    review_status varchar(20) not null default 'VERIFIED',
    created_at timestamp(6) not null default current_timestamp,
    primary key (planner_meal_id, diet_type_id),
    constraint ck_meal_diet_source check (
        classification_source in ('MANUAL', 'AUTO_KEYWORD', 'IMPORTED')
    ),
    constraint ck_meal_diet_review check (
        review_status in ('PENDING_REVIEW', 'VERIFIED', 'REJECTED')
    )
);

create table if not exists public.allergens (
    allergen_id integer generated by default as identity primary key,
    code varchar(40) not null unique,
    name_en varchar(100) not null,
    name_km varchar(150),
    is_active boolean not null default true,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp
);

create table if not exists public.planner_meal_allergens (
    planner_meal_id integer not null references public.planner_meals(planner_meal_id) on delete cascade,
    allergen_id integer not null references public.allergens(allergen_id) on delete cascade,
    presence_status varchar(20) not null default 'MAY_CONTAIN',
    classification_source varchar(20) not null default 'MANUAL',
    review_status varchar(20) not null default 'VERIFIED',
    created_at timestamp(6) not null default current_timestamp,
    primary key (planner_meal_id, allergen_id),
    constraint ck_meal_allergen_presence check (presence_status in ('CONTAINS', 'MAY_CONTAIN')),
    constraint ck_meal_allergen_source check (
        classification_source in ('MANUAL', 'AUTO_KEYWORD', 'IMPORTED')
    ),
    constraint ck_meal_allergen_review check (
        review_status in ('PENDING_REVIEW', 'VERIFIED', 'REJECTED')
    )
);

create table if not exists public.health_conditions (
    health_condition_id integer generated by default as identity primary key,
    code varchar(50) not null unique,
    name_en varchar(120) not null,
    name_km varchar(180),
    disclaimer_en text not null,
    is_active boolean not null default true,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp
);

create table if not exists public.planner_meal_health_guidance (
    planner_meal_id integer not null references public.planner_meals(planner_meal_id) on delete cascade,
    health_condition_id integer not null references public.health_conditions(health_condition_id) on delete cascade,
    guidance_level varchar(20) not null,
    rationale_en text not null,
    evidence_url varchar(500),
    review_status varchar(20) not null default 'PENDING_REVIEW',
    reviewed_by varchar(150),
    reviewed_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    primary key (planner_meal_id, health_condition_id),
    constraint ck_meal_health_guidance_level check (
        guidance_level in ('PREFER', 'NEUTRAL', 'LIMIT', 'AVOID')
    ),
    constraint ck_meal_health_guidance_review check (
        review_status in (
            'PENDING_REVIEW',
            'CLINICIAN_VERIFIED',
            'REJECTED'
        )
    )
);

create table if not exists public.meal_plan_feedback (
    meal_plan_feedback_id integer generated by default as identity primary key,
    meal_plan_id integer not null references public.meal_plans(meal_plan_id) on delete cascade,
    user_id integer not null references public.users(user_id) on delete cascade,
    rating smallint,
    outcome varchar(20) not null,
    skip_reason varchar(80),
    hunger_before smallint,
    fullness_after smallint,
    comment_text varchar(500),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    constraint uk_meal_plan_feedback_user unique (meal_plan_id, user_id),
    constraint ck_meal_feedback_rating check (
        rating is null
        or rating between 1
        and 5
    ),
    constraint ck_meal_feedback_outcome check (
        outcome in ('EATEN', 'PARTIALLY_EATEN', 'SKIPPED')
    ),
    constraint ck_meal_feedback_hunger check (
        hunger_before is null
        or hunger_before between 1
        and 5
    ),
    constraint ck_meal_feedback_fullness check (
        fullness_after is null
        or fullness_after between 1
        and 5
    )
);

create table if not exists public.meal_recommendation_audits (
    recommendation_audit_id bigint generated by default as identity primary key,
    user_id integer not null references public.users(user_id) on delete cascade,
    planner_meal_id integer not null references public.planner_meals(planner_meal_id) on delete cascade,
    weight_goal varchar(30) not null,
    total_score numeric(10, 4) not null,
    nutrition_score numeric(10, 4),
    preference_score numeric(10, 4),
    adherence_score numeric(10, 4),
    diversity_score numeric(10, 4),
    explanation_en text,
    explanation_km text,
    input_snapshot jsonb not null default '{}' :: jsonb,
    model_version varchar(50) not null,
    created_at timestamp(6) not null default current_timestamp,
    constraint ck_recommendation_audit_goal check (
        weight_goal in ('LOSE_WEIGHT', 'MAINTAIN_HEALTH', 'GAIN_WEIGHT')
    )
);

create table if not exists public.nutrition_evidence_sources (
    evidence_source_id integer generated by default as identity primary key,
    code varchar(50) not null unique,
    title varchar(255) not null,
    organization varchar(120) not null,
    source_url varchar(500) not null,
    guidance_summary text not null,
    accessed_on date not null,
    is_active boolean not null default true
);

insert into
    public.diet_types (code, name_en, name_km, description_en)
values
    (
        'BALANCED',
        'Balanced',
        'អាហារមានតុល្យភាព',
        'A varied eating pattern balancing energy and macronutrients.'
    ),
    (
        'VEGETARIAN',
        'Vegetarian',
        'អាហារបួស',
        'Excludes meat, poultry, fish, and shellfish.'
    ),
    (
        'VEGAN',
        'Vegan',
        'អាហារបួសសុទ្ធ',
        'Excludes animal-derived ingredients.'
    ),
    (
        'HIGH_PROTEIN',
        'High protein',
        'ប្រូតេអ៊ីនខ្ពស់',
        'Meal containing at least 25 grams of protein per serving.'
    ) on conflict (code) do nothing;

insert into
    public.allergens (code, name_en, name_km)
values
    ('MILK', 'Milk', 'ទឹកដោះគោ'),
    ('EGG', 'Egg', 'ស៊ុត'),
    ('PEANUT', 'Peanut', 'សណ្ដែកដី'),
    ('TREE_NUT', 'Tree nut', 'គ្រាប់ធញ្ញជាតិដើមឈើ'),
    ('SOY', 'Soy', 'សណ្តែកសៀង'),
    ('WHEAT', 'Wheat', 'ស្រូវសាលី'),
    ('FISH', 'Fish', 'ត្រី'),
    ('SHELLFISH', 'Shellfish', 'គ្រឿងសមុទ្រមានសំបក'),
    ('SESAME', 'Sesame', 'ល្ង') on conflict (code) do nothing;

insert into
    public.health_conditions (code, name_en, name_km, disclaimer_en)
values
    (
        'DIABETES',
        'Diabetes',
        'ជំងឺទឹកនោមផ្អែម',
        'Meal guidance is educational only and must be reviewed by a qualified clinician.'
    ),
    (
        'HYPERTENSION',
        'High blood pressure',
        'ជំងឺលើសឈាម',
        'Meal guidance is educational only and must be reviewed by a qualified clinician.'
    ),
    (
        'HIGH_CHOLESTEROL',
        'High cholesterol',
        'កូឡេស្តេរ៉ុលខ្ពស់',
        'Meal guidance is educational only and must be reviewed by a qualified clinician.'
    ),
    (
        'KIDNEY_DISEASE',
        'Kidney disease',
        'ជំងឺតម្រងនោម',
        'Individual requirements vary; guidance must be provided by a qualified clinician.'
    ) on conflict (code) do nothing;

insert into
    public.nutrition_evidence_sources (
        code,
        title,
        organization,
        source_url,
        guidance_summary,
        accessed_on
    )
values
    (
        'WHO_HEALTHY_DIET_2026',
        'Healthy diet',
        'World Health Organization',
        'https://www.who.int/news-room/fact-sheets/detail/healthy-diet',
        'Healthy diets emphasize adequacy, balance, moderation and diversity; adults should generally limit free sugars and sodium and obtain dietary fibre from varied whole foods.',
        date '2026-09-26'
    ),
    (
        'WHO_CARBOHYDRATE_2023',
        'Carbohydrate intake for adults and children',
        'World Health Organization',
        'https://www.who.int/publications/i/item/9789240073593',
        'Carbohydrate quality should emphasize whole grains, vegetables, fruits and pulses, with at least 25 g naturally occurring dietary fibre daily for people older than 10 years.',
        date '2026-09-26'
    ),
    (
        'CDC_WEIGHT_2025',
        'Steps for Losing Weight',
        'Centers for Disease Control and Prevention',
        'https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html',
        'Healthy weight management should be gradual and personalized, considering nutrition, activity, sleep, stress, medicines and medical conditions.',
        date '2026-09-26'
    ) on conflict (code) do nothing;

-- All active meals are candidates for a balanced pattern. Keyword-derived
-- vegetarian/vegan labels remain pending review so the UI can distinguish
-- inference from verified dietary classification.
insert into
    public.planner_meal_diet_types (
        planner_meal_id,
        diet_type_id,
        classification_source,
        review_status
    )
select
    pm.planner_meal_id,
    dt.diet_type_id,
    'AUTO_KEYWORD',
    'PENDING_REVIEW'
from
    public.planner_meals pm
    join public.diet_types dt on dt.code = 'BALANCED'
where
    pm.is_active = true on conflict (planner_meal_id, diet_type_id) do nothing;

insert into
    public.planner_meal_diet_types (
        planner_meal_id,
        diet_type_id,
        classification_source,
        review_status
    )
select
    pm.planner_meal_id,
    dt.diet_type_id,
    'AUTO_KEYWORD',
    'PENDING_REVIEW'
from
    public.planner_meals pm
    join public.diet_types dt on dt.code = 'HIGH_PROTEIN'
where
    pm.is_active = true
    and pm.protein_grams >= 25 on conflict (planner_meal_id, diet_type_id) do nothing;

-- Conservative allergen candidates inferred from English ingredient/name text.
-- MAY_CONTAIN + PENDING_REVIEW prevents unsafe use as a definitive allergy label.
with meal_text as (
    select
        planner_meal_id,
        lower(
            concat_ws(' ', name_en, ingredients_text, tags_text)
        ) as searchable
    from
        public.planner_meals
    where
        is_active = true
),
candidates as (
    select
        planner_meal_id,
        'MILK' as code
    from
        meal_text
    where
        searchable ~ '(milk|yogurt|cheese|butter|cream)'
    union
    select
        planner_meal_id,
        'EGG'
    from
        meal_text
    where
        searchable ~ '(^|[^a-z])egg([^a-z]|$)'
    union
    select
        planner_meal_id,
        'PEANUT'
    from
        meal_text
    where
        searchable ~ 'peanut'
    union
    select
        planner_meal_id,
        'TREE_NUT'
    from
        meal_text
    where
        searchable ~ '(almond|cashew|walnut|pistachio|hazelnut|mixed nuts| nuts)'
    union
    select
        planner_meal_id,
        'SOY'
    from
        meal_text
    where
        searchable ~ '(soy|tofu|tempeh)'
    union
    select
        planner_meal_id,
        'WHEAT'
    from
        meal_text
    where
        searchable ~ '(wheat|bread|pasta|noodle|flour|toast)'
    union
    select
        planner_meal_id,
        'FISH'
    from
        meal_text
    where
        searchable ~ '(fish|salmon|tuna|sardine|mackerel)'
    union
    select
        planner_meal_id,
        'SHELLFISH'
    from
        meal_text
    where
        searchable ~ '(shrimp|prawn|crab|lobster|shellfish)'
    union
    select
        planner_meal_id,
        'SESAME'
    from
        meal_text
    where
        searchable ~ '(sesame|tahini)'
)
insert into
    public.planner_meal_allergens (
        planner_meal_id,
        allergen_id,
        presence_status,
        classification_source,
        review_status
    )
select
    c.planner_meal_id,
    a.allergen_id,
    'MAY_CONTAIN',
    'AUTO_KEYWORD',
    'PENDING_REVIEW'
from
    candidates c
    join public.allergens a on a.code = c.code on conflict (planner_meal_id, allergen_id) do nothing;

create index if not exists idx_planner_meal_diets_type on public.planner_meal_diet_types (diet_type_id, planner_meal_id);

create index if not exists idx_planner_meal_allergens_allergen on public.planner_meal_allergens (allergen_id, planner_meal_id);

create index if not exists idx_planner_meal_health_condition on public.planner_meal_health_guidance (health_condition_id, guidance_level);

create index if not exists idx_meal_feedback_user_created on public.meal_plan_feedback (user_id, created_at desc);

create index if not exists idx_recommendation_audit_user_created on public.meal_recommendation_audits (user_id, created_at desc);

create index if not exists idx_recommendation_audit_meal on public.meal_recommendation_audits (planner_meal_id, created_at desc);

alter table
    public.diet_types enable row level security;

alter table
    public.planner_meal_diet_types enable row level security;

alter table
    public.allergens enable row level security;

alter table
    public.planner_meal_allergens enable row level security;

alter table
    public.health_conditions enable row level security;

alter table
    public.planner_meal_health_guidance enable row level security;

alter table
    public.meal_plan_feedback enable row level security;

alter table
    public.meal_recommendation_audits enable row level security;

alter table
    public.nutrition_evidence_sources enable row level security;
