insert into
    public.planner_meal_categories (planner_meal_id, category_id)
select
    pm.planner_meal_id,
    pm.category_id
from
    public.planner_meals pm
where
    pm.category_id is not null on conflict (planner_meal_id, category_id) do nothing;

alter table
    public.planner_meal_weight_goals
add
    column if not exists classification_source varchar(20) not null default 'LEGACY',
add
    column if not exists review_status varchar(20) not null default 'PENDING_REVIEW',
add
    column if not exists rationale varchar(500),
add
    column if not exists created_at timestamp(6) not null default current_timestamp,
add
    column if not exists reviewed_at timestamp(6),
add
    column if not exists reviewed_by varchar(150);

do $ $ begin if not exists (
    select
        1
    from
        pg_constraint
    where
        conname = 'ck_meal_goal_classification_source'
) then
alter table
    public.planner_meal_weight_goals
add
    constraint ck_meal_goal_classification_source check (
        classification_source in ('LEGACY', 'MANUAL', 'AUTO_RULE', 'IMPORTED')
    );

end if;

if not exists (
    select
        1
    from
        pg_constraint
    where
        conname = 'ck_meal_goal_review_status'
) then
alter table
    public.planner_meal_weight_goals
add
    constraint ck_meal_goal_review_status check (
        review_status in ('PENDING_REVIEW', 'VERIFIED', 'REJECTED')
    );

end if;

end $ $;

-- Add conservative weight-loss candidates without removing manual/legacy goals.
-- This is a catalog heuristic (250-450 kcal and >=18 g protein per serving),
-- not an individualized prescription. Every inferred row requires review.
insert into
    public.planner_meal_weight_goals (
        planner_meal_id,
        weight_goal,
        classification_source,
        review_status,
        rationale
    )
select
    pm.planner_meal_id,
    'LOSE_WEIGHT',
    'AUTO_RULE',
    'PENDING_REVIEW',
    concat(
        'Catalog candidate: ',
        round(pm.calories, 0),
        ' kcal and ',
        round(pm.protein_grams, 0),
        ' g protein per serving. Requires dietitian/admin review.'
    )
from
    public.planner_meals pm
where
    pm.is_active = true
    and pm.calories between 250
    and 450
    and pm.protein_grams >= 18 on conflict (planner_meal_id, weight_goal) do nothing;

create index if not exists idx_planner_meal_goals_review on public.planner_meal_weight_goals (review_status, weight_goal, planner_meal_id);

create table if not exists public.planner_catalog_reviews (
    planner_catalog_review_id bigint generated by default as identity primary key,
    planner_meal_id integer not null references public.planner_meals(planner_meal_id) on delete cascade,
    review_area varchar(30) not null,
    status varchar(20) not null default 'PENDING',
    reviewer_user_id integer references public.users(user_id) on delete
    set
        null,
        review_note varchar(500),
        reviewed_at timestamp(6),
        created_at timestamp(6) not null default current_timestamp,
        updated_at timestamp(6) not null default current_timestamp,
        constraint uk_planner_catalog_review_area unique (planner_meal_id, review_area),
        constraint ck_planner_catalog_review_area check (
            review_area in (
                'NUTRITION',
                'WEIGHT_GOAL',
                'DIET',
                'ALLERGEN',
                'HEALTH_GUIDANCE'
            )
        ),
        constraint ck_planner_catalog_review_status check (
            status in (
                'PENDING',
                'APPROVED',
                'NEEDS_CHANGES',
                'REJECTED'
            )
        )
);

insert into
    public.planner_catalog_reviews (planner_meal_id, review_area)
select
    pm.planner_meal_id,
    area.review_area
from
    public.planner_meals pm
    cross join (
        values
            ('NUTRITION'),
            ('WEIGHT_GOAL'),
            ('DIET'),
            ('ALLERGEN')
    ) as area(review_area)
where
    pm.is_active = true on conflict (planner_meal_id, review_area) do nothing;

create index if not exists idx_planner_catalog_reviews_queue on public.planner_catalog_reviews (status, review_area, created_at, planner_meal_id);

alter table
    public.planner_catalog_reviews enable row level security;

create
or replace view public.planner_meal_personalization_catalog with (security_invoker = true) as
select
    pm.planner_meal_id,
    pm.name_en,
    pm.name_km,
    pm.is_active,
    mc.category_name as primary_category,
    pm.calories,
    pm.protein_grams,
    pm.carbs_grams,
    pm.fat_grams,
    pm.fiber_grams,
    pm.sugar_grams,
    pm.sodium_mg,
    pm.saturated_fat_grams,
    pm.serving_size,
    pm.serving_unit,
    pm.nutrition_data_quality,
    coalesce(
        (
            select
                array_agg(
                    wg.weight_goal
                    order by
                        wg.weight_goal
                )
            from
                public.planner_meal_weight_goals wg
            where
                wg.planner_meal_id = pm.planner_meal_id
                and wg.review_status <> 'REJECTED'
        ),
        array [] :: varchar []
    ) as weight_goals,
    coalesce(
        (
            select
                array_agg(
                    dt.code
                    order by
                        dt.code
                )
            from
                public.planner_meal_diet_types pmd
                join public.diet_types dt on dt.diet_type_id = pmd.diet_type_id
            where
                pmd.planner_meal_id = pm.planner_meal_id
                and pmd.review_status <> 'REJECTED'
        ),
        array [] :: varchar []
    ) as diet_types,
    coalesce(
        (
            select
                array_agg(
                    a.code
                    order by
                        a.code
                )
            from
                public.planner_meal_allergens pma
                join public.allergens a on a.allergen_id = pma.allergen_id
            where
                pma.planner_meal_id = pm.planner_meal_id
                and pma.review_status <> 'REJECTED'
        ),
        array [] :: varchar []
    ) as allergen_candidates,
    (
        (
            case
                when pm.calories is not null
                and pm.calories > 0 then 1
                else 0
            end
        ) + (
            case
                when pm.protein_grams is not null
                and pm.protein_grams > 0 then 1
                else 0
            end
        ) + (
            case
                when pm.carbs_grams is not null
                and pm.carbs_grams > 0 then 1
                else 0
            end
        ) + (
            case
                when pm.fat_grams is not null
                and pm.fat_grams > 0 then 1
                else 0
            end
        ) + (
            case
                when pm.fiber_grams is not null then 1
                else 0
            end
        ) + (
            case
                when pm.sugar_grams is not null then 1
                else 0
            end
        ) + (
            case
                when pm.sodium_mg is not null then 1
                else 0
            end
        ) + (
            case
                when pm.serving_size is not null
                and pm.serving_unit is not null then 1
                else 0
            end
        )
    ) * 12.5 as nutrition_completeness_percent,
    (
        select
            count(*)
        from
            public.weekly_meal_recommendations wr
        where
            wr.planner_meal_id = pm.planner_meal_id
            and wr.is_active = true
    ) as active_schedule_count,
    (
        select
            count(*)
        from
            public.planner_catalog_reviews pcr
        where
            pcr.planner_meal_id = pm.planner_meal_id
            and pcr.status = 'PENDING'
    ) as pending_review_count
from
    public.planner_meals pm
    join public.meal_categories mc on mc.category_id = pm.category_id;

create
or replace view public.planner_catalog_quality_issues with (security_invoker = true) as
select
    planner_meal_id,
    name_en,
    'MISSING_EXTENDED_NUTRITION' :: varchar as issue_code,
    'Fiber, sugar, sodium, or serving data requires a verified source.' :: varchar as issue_detail
from
    public.planner_meal_personalization_catalog
where
    fiber_grams is null
    or sugar_grams is null
    or sodium_mg is null
union
all
select
    planner_meal_id,
    name_en,
    'UNVERIFIED_NUTRITION' :: varchar,
    'Nutrition data has not been verified against a cited source.' :: varchar
from
    public.planner_meal_personalization_catalog
where
    nutrition_data_quality = 'UNVERIFIED'
union
all
select
    planner_meal_id,
    name_en,
    'NOT_SCHEDULED' :: varchar,
    'Active meal is not visible in weekly recommendations.' :: varchar
from
    public.planner_meal_personalization_catalog
where
    is_active = true
    and active_schedule_count = 0;
