create table if not exists public.planner_meal_ingredients (
    planner_meal_ingredient_id integer generated by default as identity primary key,
    planner_meal_id integer not null references public.planner_meals(planner_meal_id) on delete cascade,
    ingredient_id integer not null references public.ingredients(ingredient_id),
    quantity numeric(10, 2),
    unit varchar(30),
    preparation_note varchar(150),
    display_order integer not null,
    created_at timestamp without time zone not null default current_timestamp,
    constraint uk_planner_meal_ingredient unique (planner_meal_id, ingredient_id),
    constraint uk_planner_meal_ingredient_order unique (planner_meal_id, display_order),
    constraint ck_planner_meal_ingredient_quantity check (
        quantity is null
        or quantity >= 0
    )
);

create index if not exists idx_planner_meal_ingredients_meal on public.planner_meal_ingredients(planner_meal_id, display_order);

create index if not exists idx_planner_meal_ingredients_ingredient on public.planner_meal_ingredients(ingredient_id);

alter table
    public.planner_meal_ingredients enable row level security;

-- Seed catalog entries from existing semicolon/newline lists. More detailed
-- quantity/unit normalization is performed by PlannerIngredientNormalizationService.
with raw_parts as (
    select
        pm.planner_meal_id,
        row_number() over (
            partition by pm.planner_meal_id
            order by
                part.ordinality
        ) as display_order,
        trim(part.value) as raw_value
    from
        public.planner_meals pm
        cross join lateral regexp_split_to_table(
            coalesce(pm.ingredients_text, ''),
            E '[;\\r\\n]+'
        ) with ordinality as part(value, ordinality)
),
parsed as (
    select
        planner_meal_id,
        display_order,
        trim(
            case
                when raw_value like '%|%' then split_part(raw_value, '|', 1)
                when raw_value ~* '^\\s*[0-9]+([.][0-9]+)?\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)?\\s+.+' then regexp_replace(
                    raw_value,
                    '^\\s*[0-9]+([.][0-9]+)?\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)?\\s+',
                    '',
                    'i'
                )
                else raw_value
            end
        ) as ingredient_name,
        case
            when raw_value like '%|%'
            and trim(split_part(raw_value, '|', 2)) ~ '^[0-9]+([.][0-9]+)?$' then trim(split_part(raw_value, '|', 2)) :: numeric
            when raw_value ~ '^\\s*[0-9]+([.][0-9]+)?' then substring(
                raw_value
                from
                    '^\\s*([0-9]+([.][0-9]+)?)'
            ) :: numeric
            else null
        end as quantity,
        nullif(
            trim(
                case
                    when raw_value like '%|%' then split_part(raw_value, '|', 3)
                    when raw_value ~* '^\\s*[0-9]+[.]?[0-9]*\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)\\s+.*$' then regexp_replace(
                        raw_value,
                        '^\\s*[0-9]+[.]?[0-9]*\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)\\s+.*$',
                        '\\1',
                        'i'
                    )
                    else null
                end
            ),
            ''
        ) as unit
    from
        raw_parts
    where
        raw_value <> ''
),
unique_names as (
    select
        distinct on (lower(ingredient_name)) ingredient_name,
        unit
    from
        parsed
    where
        ingredient_name <> ''
    order by
        lower(ingredient_name),
        ingredient_name
)
insert into
    public.ingredients (ingredient_name, ingredient_type, default_unit)
select
    ingredient_name,
    'General',
    unit
from
    unique_names candidate
where
    not exists (
        select
            1
        from
            public.ingredients existing
        where
            lower(existing.ingredient_name) = lower(candidate.ingredient_name)
    ) on conflict (ingredient_name) do nothing;

with raw_parts as (
    select
        pm.planner_meal_id,
        part.ordinality :: integer as display_order,
        trim(part.value) as raw_value
    from
        public.planner_meals pm
        cross join lateral regexp_split_to_table(
            coalesce(pm.ingredients_text, ''),
            E '[;\\r\\n]+'
        ) with ordinality as part(value, ordinality)
),
parsed as (
    select
        planner_meal_id,
        display_order,
        trim(
            case
                when raw_value like '%|%' then split_part(raw_value, '|', 1)
                when raw_value ~* '^\\s*[0-9]+([.][0-9]+)?\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)?\\s+.+' then regexp_replace(
                    raw_value,
                    '^\\s*[0-9]+([.][0-9]+)?\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)?\\s+',
                    '',
                    'i'
                )
                else raw_value
            end
        ) as ingredient_name,
        case
            when raw_value like '%|%'
            and trim(split_part(raw_value, '|', 2)) ~ '^[0-9]+([.][0-9]+)?$' then trim(split_part(raw_value, '|', 2)) :: numeric
            when raw_value ~ '^\\s*[0-9]+([.][0-9]+)?' then substring(
                raw_value
                from
                    '^\\s*([0-9]+([.][0-9]+)?)'
            ) :: numeric
            else null
        end as quantity,
        nullif(
            trim(
                case
                    when raw_value like '%|%' then split_part(raw_value, '|', 3)
                    when raw_value ~* '^\\s*[0-9]+[.]?[0-9]*\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)\\s+.*$' then regexp_replace(
                        raw_value,
                        '^\\s*[0-9]+[.]?[0-9]*\\s*(kg|mg|g|ml|l|tsp|tbsp|cups?|pieces?|pcs?)\\s+.*$',
                        '\\1',
                        'i'
                    )
                    else null
                end
            ),
            ''
        ) as unit
    from
        raw_parts
    where
        raw_value <> ''
),
resolved as (
    select
        parsed.*,
        ingredient.ingredient_id,
        row_number() over (
            partition by parsed.planner_meal_id,
            ingredient.ingredient_id
            order by
                parsed.display_order
        ) as duplicate_number
    from
        parsed
        join lateral (
            select
                i.ingredient_id
            from
                public.ingredients i
            where
                lower(i.ingredient_name) = lower(parsed.ingredient_name)
            order by
                i.ingredient_id
            limit
                1
        ) ingredient on true
    where
        parsed.ingredient_name <> ''
)
insert into
    public.planner_meal_ingredients (
        planner_meal_id,
        ingredient_id,
        quantity,
        unit,
        display_order
    )
select
    planner_meal_id,
    ingredient_id,
    quantity,
    unit,
    row_number() over (
        partition by planner_meal_id
        order by
            display_order
    ) :: integer
from
    resolved
where
    duplicate_number = 1 on conflict do nothing;
