create table public.reports (
    report_id integer generated by default as identity primary key,
    reporter_user_id integer not null references public.users(user_id),
    reported_user_id integer not null references public.users(user_id),
    report_type varchar(20) not null,
    target_id integer not null,
    reason varchar(60) not null,
    description varchar(500),
    content_snapshot varchar(1000),
    status varchar(20) not null default 'PENDING',
    severity varchar(20) not null default 'MEDIUM',
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    reviewed_at timestamp(6),
    reviewed_by integer references public.users(user_id),
    admin_note varchar(1000),
    constraint ck_reports_type check (report_type in ('PROFILE','POST','COMMENT')),
    constraint ck_reports_status check (status in ('PENDING','UNDER_REVIEW','RESOLVED','DISMISSED')),
    constraint ck_reports_severity check (severity in ('LOW','MEDIUM','HIGH','CRITICAL')),
    constraint ck_reports_not_self check (reporter_user_id <> reported_user_id),
    constraint ck_reports_description_length check (description is null or char_length(description) <= 500)
);

create unique index uq_reports_active_reporter_target
    on public.reports(reporter_user_id, report_type, target_id)
    where status in ('PENDING','UNDER_REVIEW');
create index idx_reports_review_queue on public.reports(status, severity, created_at);
create index idx_reports_reported_user on public.reports(reported_user_id, created_at desc);

create table public.moderation_actions (
    action_id integer generated by default as identity primary key,
    report_id integer references public.reports(report_id),
    target_user_id integer not null references public.users(user_id),
    admin_user_id integer not null references public.users(user_id),
    action_type varchar(30) not null,
    reason varchar(60) not null,
    admin_note varchar(1000),
    starts_at timestamp(6),
    expires_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    reversed_at timestamp(6),
    reversed_by integer references public.users(user_id),
    constraint ck_moderation_action_type check (action_type in ('WARNING','CONTENT_HIDDEN','CONTENT_REMOVED','POST_RESTRICTED','COMMENT_RESTRICTED','ACCOUNT_RESTRICTED','SUSPENDED','BANNED')),
    constraint ck_moderation_dates check (expires_at is null or starts_at is null or expires_at > starts_at)
);
create index idx_moderation_actions_user on public.moderation_actions(target_user_id, created_at desc);

create table public.moderation_appeals (
    appeal_id integer generated by default as identity primary key,
    moderation_action_id integer not null references public.moderation_actions(action_id),
    user_id integer not null references public.users(user_id),
    reason varchar(500) not null,
    status varchar(20) not null default 'PENDING',
    admin_note varchar(1000),
    created_at timestamp(6) not null default current_timestamp,
    reviewed_at timestamp(6),
    reviewed_by integer references public.users(user_id),
    constraint uq_moderation_appeal_action_user unique (moderation_action_id, user_id),
    constraint ck_appeal_status check (status in ('PENDING','APPROVED','REJECTED'))
);
create index idx_moderation_appeals_status on public.moderation_appeals(status, created_at);
