-- Clean development baseline generated from the active JPA model.
-- User meal posts are the aggregate root; ingredients and cooking steps are children.

create table public.ai_food_analyses (ai_food_analysis_id integer generated by default as identity, completion_tokens integer, confidence_score numeric(38,2), corrected_serving_size numeric(10,2), database_matched boolean, nutrition_fallback_used boolean, prompt_tokens integer, user_confirmed boolean, user_id integer not null, created_at timestamp(6) not null, feedback_at timestamp(6), latency_ms bigint, status varchar(20) not null, corrected_serving_unit varchar(40), prompt_version varchar(50), detected_serving_text varchar(100), model_name varchar(120), corrected_food_name varchar(150), detected_food_name varchar(150), analysis_text varchar(1000), input_text varchar(255) not null, primary key (ai_food_analysis_id));
create table public.ai_food_analysis_nutrients (ai_food_analysis_id integer not null, analysis_nutrient_id integer generated by default as identity, estimated_amount numeric(38,2) not null, nutrient_id integer not null, primary key (analysis_nutrient_id));
create table public.ai_food_suggestions (ai_food_analysis_id integer not null, ai_food_suggestion_id integer generated by default as identity, priority integer not null, suggestion_type varchar(50) not null, title varchar(150) not null, description varchar(255) not null, reason varchar(255), primary key (ai_food_suggestion_id));
create table public.ai_recipe_reviews (ai_recipe_review_id integer generated by default as identity, user_meal_post_id integer not null, created_at timestamp(6) not null, status varchar(20) not null, model_name varchar(100), summary varchar(1000), feedback varchar(255), model_response varchar(255), primary key (ai_recipe_review_id));
create table public.ai_recommendation_items (meal_id integer not null, rank_order integer not null, recommendation_id integer not null, recommendation_item_id integer generated by default as identity, created_at timestamp(6) not null, reason_text varchar(500), primary key (recommendation_item_id));
create table public.ai_recommendations (mood_id integer, recommendation_id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, status varchar(20) not null, request_text varchar(255), response_text varchar(255), primary key (recommendation_id));
create table public.auth_providers (is_active boolean not null, provider_id integer generated by default as identity, provider_name varchar(50) not null unique, primary key (provider_id));
create table public.comment_likes (comment_id integer not null, comment_like_id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, primary key (comment_like_id));
create table public.daily_nutrient_totals (consumed_amount numeric(38,2) not null, daily_nutrient_total_id integer generated by default as identity, daily_summary_id integer not null, goal_amount numeric(38,2) not null, nutrient_id integer not null, percentage numeric(38,2), primary key (daily_nutrient_total_id));
create table public.daily_wellness_summaries (daily_summary_id integer generated by default as identity, mood_id integer, summary_date date not null, user_id integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, balance_status varchar(30), ai_insight_text varchar(255), primary key (daily_summary_id));
create table public.faqs (faq_id integer generated by default as identity, is_active boolean not null, sort_order integer not null, updated_at timestamp(6) not null, answer varchar(255) not null, question varchar(255) not null, primary key (faq_id));
create table public.follows (follow_id integer generated by default as identity, follower_user_id integer not null, following_user_id integer not null, requested_at timestamp(6) not null, responded_at timestamp(6), status varchar(20) not null, primary key (follow_id));
create table public.food_nutrition (calories numeric(10,2) not null, carbs numeric(10,2) not null, fat numeric(10,2) not null, fiber numeric(10,2), id integer generated by default as identity, is_active boolean not null, protein numeric(10,2) not null, serving_size numeric(10,2) not null, sodium numeric(10,2), sugar numeric(10,2) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, serving_unit varchar(40) not null, name varchar(150) not null unique, aliases TEXT, image_url varchar(255), primary key (id));
create table public.ingredients (ingredient_id integer generated by default as identity, default_unit varchar(30), ingredient_type varchar(50), ingredient_name varchar(100) not null unique, description varchar(255), image_url varchar(255), primary key (ingredient_id));
create table public.legal_documents (is_active boolean not null, legal_document_id integer generated by default as identity, effective_at timestamp(6) not null, document_type varchar(30) not null, version varchar(30) not null, title varchar(150) not null, content varchar(255) not null, primary key (legal_document_id));
create table public.meal_categories (category_id integer generated by default as identity, is_active boolean not null, sort_order integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, category_name varchar(50) not null unique, description varchar(255), primary key (category_id));
create table public.meal_favorites (meal_favorite_id integer generated by default as identity, meal_id integer not null, user_id integer not null, saved_at timestamp(6) not null, primary key (meal_favorite_id));
create table public.meal_ingredients (display_order integer not null, ingredient_id integer not null, meal_id integer not null, meal_ingredient_id integer generated by default as identity, quantity numeric(38,2), unit varchar(30), preparation_note varchar(150), primary key (meal_ingredient_id));
create table public.meal_log_nutrients (amount numeric(38,2) not null, meal_log_id integer not null, meal_log_nutrient_id integer generated by default as identity, nutrient_id integer not null, primary key (meal_log_nutrient_id));
create table public.meal_log_types (meal_log_type_id integer generated by default as identity, sort_order integer not null, meal_log_type_name varchar(50) not null unique, primary key (meal_log_type_id));
create table public.meal_logs (ai_food_analysis_id integer, meal_id integer, meal_log_id integer generated by default as identity, meal_log_type_id integer not null, quantity numeric(38,2) not null, serving_size_id integer, user_id integer not null, created_at timestamp(6) not null, logged_at timestamp(6) not null, updated_at timestamp(6) not null, entry_method varchar(20) not null, custom_food_name varchar(150), notes varchar(255), primary key (meal_log_id));
create table public.meal_nutrition (amount_per_serving numeric(38,2) not null, meal_id integer not null, meal_nutrition_id integer generated by default as identity, nutrient_id integer not null, primary key (meal_nutrition_id));
create table public.meal_tags (meal_id integer not null, meal_tag_id integer generated by default as identity, tag_id integer not null, primary key (meal_tag_id));
create table public.meals (calories_cached numeric(38,2), category_id integer not null, cooking_time_minutes integer, created_by_user_id integer, is_published boolean not null, meal_id integer generated by default as identity, protein_grams_cached numeric(38,2), servings integer, source_user_meal_post_id integer unique, created_at timestamp(6) not null, updated_at timestamp(6) not null, approval_source varchar(20) not null, difficulty varchar(20), source_type varchar(20) not null, meal_name varchar(150) not null, description varchar(255), main_image_url varchar(255), primary key (meal_id));
create table public.moods (is_active boolean not null, mood_id integer generated by default as identity, emoji_code varchar(30), mood_name varchar(100) not null unique, primary key (mood_id));
create table public.notifications (actor_user_id integer, is_read boolean not null, notification_id integer generated by default as identity, reference_id integer, user_id integer not null, created_at timestamp(6) not null, read_at timestamp(6), notification_type varchar(50) not null, reference_type varchar(50), title varchar(150), message varchar(500) not null, primary key (notification_id));
create table public.nutrients (display_order integer not null, is_active boolean not null, is_core boolean not null, nutrient_id integer generated by default as identity, unit varchar(20) not null, nutrient_name varchar(50) not null unique, primary key (nutrient_id));
create table public.password_reset_tokens (reset_token_id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, expires_at timestamp(6) not null, used_at timestamp(6), token_hash varchar(255) not null, primary key (reset_token_id));
create table public.post_comments (comment_id integer generated by default as identity, parent_comment_id integer, user_id integer not null, user_meal_post_id integer not null, created_at timestamp(6) not null, updated_at timestamp(6), status varchar(20) not null, comment_text varchar(255) not null, primary key (comment_id));
create table public.post_favorites (post_favorite_id integer generated by default as identity, user_id integer not null, user_meal_post_id integer not null, saved_at timestamp(6) not null, primary key (post_favorite_id));
create table public.post_likes (post_like_id integer generated by default as identity, user_id integer not null, user_meal_post_id integer not null, created_at timestamp(6) not null, primary key (post_like_id), constraint uk_post_likes_user_post unique (user_id, user_meal_post_id));
create table public.post_media (display_order integer not null, post_media_id integer generated by default as identity, user_meal_post_id integer not null, media_type varchar(20) not null, media_url varchar(255) not null, primary key (post_media_id));
create table public.post_reports (comment_id integer, report_id integer generated by default as identity, report_reason_id integer not null, reported_by_user_id integer not null, reviewed_by_user_id integer, user_meal_post_id integer not null, created_at timestamp(6) not null, reviewed_at timestamp(6), moderation_action varchar(20), status varchar(20) not null, target_type varchar(20) not null, admin_note varchar(1000), primary key (report_id));
create table public.post_tags (post_tag_id integer generated by default as identity, tag_id integer not null, user_meal_post_id integer not null, primary key (post_tag_id));
create table public.push_notification_devices (user_id integer not null, device_id bigint generated by default as identity, updated_at timestamp(6) not null, platform varchar(20) not null, token varchar(512) not null unique, primary key (device_id));
create table public.recipe_ingredients (amount numeric(10,2), display_order integer not null, ingredient_id integer, recipe_ingredient_id integer generated by default as identity, user_meal_post_id integer not null, unit varchar(30), ingredient_name varchar(150) not null, preparation_note varchar(150), primary key (recipe_ingredient_id));
create table public.recipe_steps (meal_id integer, step_id integer generated by default as identity, step_number integer not null, user_meal_post_id integer, step_title varchar(150), image_url varchar(255), instruction varchar(255) not null, primary key (step_id));
create table public.recipe_tags (recipe_tag_id integer generated by default as identity, tag_id integer not null, user_meal_post_id integer not null, primary key (recipe_tag_id), constraint uk_recipe_tags_recipe_tag unique (user_meal_post_id, tag_id));
create table public.report_reasons (is_active boolean not null, report_reason_id integer generated by default as identity, reason_name varchar(100) not null unique, primary key (report_reason_id));
create table public.roles (role_id integer generated by default as identity, role_name varchar(50) not null unique, description varchar(255), primary key (role_id));
create table public.saved_recipes (saved_recipe_id integer generated by default as identity, user_id integer not null, user_meal_post_id integer not null, saved_at timestamp(6) not null, primary key (saved_recipe_id), constraint uk_saved_recipes_user_recipe unique (user_id, user_meal_post_id));
create table public.serving_sizes (is_active boolean not null, multiplier numeric(38,2) not null, serving_size_id integer generated by default as identity, serving_size_name varchar(50) not null unique, description varchar(255), primary key (serving_size_id));
create table public.support_contacts (is_active boolean not null, sort_order integer not null, support_contact_id integer generated by default as identity, contact_type varchar(20) not null, display_label varchar(100) not null, contact_value varchar(150) not null, primary key (support_contact_id));
create table public.tag_types (is_active boolean not null, tag_id integer generated by default as identity, tag_scope varchar(20) not null, tag_name varchar(100) not null unique, description varchar(255), primary key (tag_id));
create table public.user_auth_providers (provider_id integer not null, user_auth_provider_id integer generated by default as identity, user_id integer not null, linked_at timestamp(6) not null, provider_email varchar(150), provider_user_key varchar(255) not null, primary key (user_auth_provider_id));
create table public.user_meal_posts (author_user_id integer not null, cooking_time_minutes integer, meal_id integer unique, servings integer, user_meal_post_id integer generated by default as identity, created_at timestamp(6) not null, published_at timestamp(6), updated_at timestamp(6) not null, ai_status varchar(20) not null, difficulty varchar(20), status varchar(20) not null, recipe_name varchar(150) not null, ai_review_reason varchar(255), description varchar(255), main_image_url varchar(255), primary key (user_meal_post_id));
create table public.user_nutrient_goals (effective_from date not null, effective_to date, goal_amount numeric(38,2) not null, is_active boolean not null, nutrient_id integer not null, user_id integer not null, user_nutrient_goal_id integer generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, primary key (user_nutrient_goal_id));
create table public.user_profiles (date_of_birth date, user_id integer not null unique, user_profile_id integer generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, gender varchar(30), phone_number varchar(30), membership_type varchar(50), full_name varchar(150) not null, location_text varchar(150), bio varchar(300), profile_image_url varchar(255), primary key (user_profile_id));
create table public.user_recipe_ai_checks (ai_recipe_review_id integer, user_id integer not null, user_meal_post_id integer not null, user_recipe_ai_check_id integer generated by default as identity, created_at timestamp(6) not null, status varchar(20) not null, primary key (user_recipe_ai_check_id));
create table public.user_settings (email_notifications_enabled boolean not null, push_notifications_enabled boolean not null, user_id integer not null unique, user_setting_id integer generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, language_code varchar(10) not null, theme varchar(20) not null, primary key (user_setting_id));
create table public.users (is_verified boolean not null, pin_length integer, role_id integer not null, user_id integer generated by default as identity, created_at timestamp(6) not null, last_login_at timestamp(6), updated_at timestamp(6) not null, verified_at timestamp(6), status varchar(20) not null, pin_hash varchar(100), email varchar(150) unique, password_hash varchar(255), primary key (user_id));
create table public.verification_codes (attempt_count integer not null, user_id integer, verification_id integer generated by default as identity, created_at timestamp(6) not null, expires_at timestamp(6) not null, verified_at timestamp(6), delivery_method varchar(20) not null, status varchar(20) not null, purpose varchar(30) not null, destination varchar(150) not null, code_hash varchar(255) not null, primary key (verification_id));
create table public.wellness_profiles (age_cached smallint, height_cm numeric(38,2), user_id integer not null unique, weight_kg numeric(38,2), wellness_profile_id integer generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, activity_level varchar(50), primary key (wellness_profile_id));
create index public.idx_ai_recipe_reviews_meal_post_created on public.ai_recipe_reviews (user_meal_post_id, created_at);
create index public.idx_ai_recipe_reviews_status on public.ai_recipe_reviews (status);
create index public.idx_daily_wellness_user_date on public.daily_wellness_summaries (user_id, summary_date);
create index public.idx_daily_wellness_mood_id on public.daily_wellness_summaries (mood_id);
create index public.idx_meal_favorites_meal_id on public.meal_favorites (meal_id);
create index public.idx_meal_favorites_user_id on public.meal_favorites (user_id);
create index public.idx_meal_ingredients_meal_id on public.meal_ingredients (meal_id);
create index public.idx_meal_ingredients_ingredient_id on public.meal_ingredients (ingredient_id);
create index public.idx_meal_logs_user_logged_at on public.meal_logs (user_id, logged_at);
create index public.idx_meal_logs_meal_id on public.meal_logs (meal_id);
create index public.idx_meal_logs_serving_size_id on public.meal_logs (serving_size_id);
create index public.idx_meal_tags_meal_id on public.meal_tags (meal_id);
create index public.idx_meal_tags_tag_id on public.meal_tags (tag_id);
create index public.idx_meals_category_id on public.meals (category_id);
create index public.idx_meals_created_by_user_id on public.meals (created_by_user_id);
create index public.idx_meals_updated_at on public.meals (updated_at);
create index public.idx_notifications_user_created_at on public.notifications (user_id, created_at);
create index public.idx_notifications_actor_user_id on public.notifications (actor_user_id);
create index public.idx_post_comments_post_id_created_at on public.post_comments (user_meal_post_id, created_at);
create index public.idx_post_comments_user_id on public.post_comments (user_id);
create index public.idx_post_comments_parent_comment_id on public.post_comments (parent_comment_id);
create index public.idx_recipe_ingredients_meal_post_order on public.recipe_ingredients (user_meal_post_id, display_order);
create index public.idx_recipe_steps_meal_post_id on public.recipe_steps (user_meal_post_id);
create index public.idx_recipe_steps_meal_post_order on public.recipe_steps (user_meal_post_id, step_number);
create index public.idx_recipe_tags_tag_id on public.recipe_tags (tag_id);
create index public.idx_saved_recipes_meal_post_id on public.saved_recipes (user_meal_post_id);
create index public.idx_user_meal_posts_author_user_id on public.user_meal_posts (author_user_id);
create index public.idx_user_meal_posts_status_updated_at on public.user_meal_posts (status, updated_at);
create index public.idx_user_recipe_ai_checks_user_created on public.user_recipe_ai_checks (user_id, created_at);
create index public.idx_user_recipe_ai_checks_meal_post_created on public.user_recipe_ai_checks (user_meal_post_id, created_at);
alter table if exists public.ai_food_analyses add constraint FKnomd9q2buwe8g9onsly0a2ykx foreign key (user_id) references public.users;
alter table if exists public.ai_food_analysis_nutrients add constraint FKl60itpfg73y6o0do88dul9x9f foreign key (ai_food_analysis_id) references public.ai_food_analyses;
alter table if exists public.ai_food_analysis_nutrients add constraint FK9aw8i2ej1dbm1qrn1bcujhvio foreign key (nutrient_id) references public.nutrients;
alter table if exists public.ai_food_suggestions add constraint FK8a3qa5ww9y3pkywtquk120vlc foreign key (ai_food_analysis_id) references public.ai_food_analyses;
alter table if exists public.ai_recipe_reviews add constraint FKq7y2e8psxltrm1ekylmwgsa8g foreign key (user_meal_post_id) references public.user_meal_posts;
alter table if exists public.ai_recommendation_items add constraint FKltlae8gfcmgck8311gxy66bhh foreign key (meal_id) references public.meals;
alter table if exists public.ai_recommendation_items add constraint FKguk7vn7bvde21wew6umyo6fe2 foreign key (recommendation_id) references public.ai_recommendations;
alter table if exists public.ai_recommendations add constraint FKh8ow7dh1xu8uvu6hghxxmhxp8 foreign key (mood_id) references public.moods;
alter table if exists public.ai_recommendations add constraint FKawyie1nntxfgm46oh0tdk91q5 foreign key (user_id) references public.users;
alter table if exists public.comment_likes add constraint FK6q90s6gsqjadphkngyf3y0fop foreign key (comment_id) references public.post_comments;
alter table if exists public.comment_likes add constraint FK6h3lbneryl5pyb9ykaju7werx foreign key (user_id) references public.users;
alter table if exists public.daily_nutrient_totals add constraint FK8s3egdd7n5cpmns6x2w1bctqq foreign key (daily_summary_id) references public.daily_wellness_summaries;
alter table if exists public.daily_nutrient_totals add constraint FKfc4v84c4k0leogpai4bykp13p foreign key (nutrient_id) references public.nutrients;
alter table if exists public.daily_wellness_summaries add constraint FKoq95w5tx3b70ybbxfps204mmw foreign key (mood_id) references public.moods;
alter table if exists public.daily_wellness_summaries add constraint FKev3jxkdbs5i7rv9vnjdh99yyq foreign key (user_id) references public.users;
alter table if exists public.follows add constraint FKe53q5i2pk9a4rddeb47cac9rd foreign key (follower_user_id) references public.users;
alter table if exists public.follows add constraint FKk1b1yn6h0224kelm91qetqxen foreign key (following_user_id) references public.users;
alter table if exists public.meal_favorites add constraint FKtkwo3071wod0wuofbssnrlq6e foreign key (meal_id) references public.meals;
alter table if exists public.meal_favorites add constraint FK5jotc7h3f18406y1oq60uonuk foreign key (user_id) references public.users;
alter table if exists public.meal_ingredients add constraint FKr6k76rkha8flnalxb1dbvnsvk foreign key (ingredient_id) references public.ingredients;
alter table if exists public.meal_ingredients add constraint FKojifbyy4w8xj272rus01j7b7g foreign key (meal_id) references public.meals;
alter table if exists public.meal_log_nutrients add constraint FKaphcg9shvoym8xu7hi5bvuwxj foreign key (meal_log_id) references public.meal_logs;
alter table if exists public.meal_log_nutrients add constraint FKt57gebdsx66hr63tft0a8get4 foreign key (nutrient_id) references public.nutrients;
alter table if exists public.meal_logs add constraint FKmpvp5aa8rllnkspmmby6oox2i foreign key (ai_food_analysis_id) references public.ai_food_analyses;
alter table if exists public.meal_logs add constraint FKgg6at6ji0hpj3ir9vlnx2jgpi foreign key (meal_id) references public.meals;
alter table if exists public.meal_logs add constraint FKg5gwdhhlemfwin6n2wjhs8bbw foreign key (meal_log_type_id) references public.meal_log_types;
alter table if exists public.meal_logs add constraint FK9ts93kgoqj7uyp7htjt3983bv foreign key (serving_size_id) references public.serving_sizes;
alter table if exists public.meal_logs add constraint FKp3xr0rnprrvb2yy6bbc3uypk9 foreign key (user_id) references public.users;
alter table if exists public.meal_nutrition add constraint FKjuhdpoqbk7qoqtjlbo9u7xem9 foreign key (meal_id) references public.meals;
alter table if exists public.meal_nutrition add constraint FKhf28i2x3q4dfty0o9luoc3tlx foreign key (nutrient_id) references public.nutrients;
alter table if exists public.meal_tags add constraint FKjro8tb4giftqb8wbcs3ul1g1l foreign key (meal_id) references public.meals;
alter table if exists public.meal_tags add constraint FKfp1vs026awk13eiy00i2df2hs foreign key (tag_id) references public.tag_types;
alter table if exists public.meals add constraint FKh2pr37nr7dwstqofw1ysefx4r foreign key (category_id) references public.meal_categories;
alter table if exists public.meals add constraint FKfxbm0phcsxgfobco1wjo7yjtr foreign key (created_by_user_id) references public.users;
alter table if exists public.meals add constraint FKnkb3mpj1cckcx74iogg0ahale foreign key (source_user_meal_post_id) references public.user_meal_posts;
alter table if exists public.notifications add constraint FKc8j0u0suv08ytbh1lamjb5n28 foreign key (actor_user_id) references public.users;
alter table if exists public.notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references public.users;
alter table if exists public.password_reset_tokens add constraint FKk3ndxg5xp6v7wd4gjyusp15gq foreign key (user_id) references public.users;
alter table if exists public.post_comments add constraint FK21q7y8a124im4g0l4aaxn4ol1 foreign key (parent_comment_id) references public.post_comments;
alter table if exists public.post_comments add constraint FKsnxoecngu89u3fh4wdrgf0f2g foreign key (user_id) references public.users;
alter table if exists public.post_favorites add constraint FKdyw3b7v5xh2sh8b05pkvb52tq foreign key (user_id) references public.users;
alter table if exists public.post_likes add constraint FKkgau5n0nlewg6o9lr4yibqgxj foreign key (user_id) references public.users;
alter table if exists public.post_reports add constraint FKm5v2ewbmla1wmgaeldmm3yf9g foreign key (comment_id) references public.post_comments;
alter table if exists public.post_reports add constraint FKsrrpmnxe84hxejf7nt2d50qjt foreign key (report_reason_id) references public.report_reasons;
alter table if exists public.post_reports add constraint FK121f4omxertppr3jhse77e0bw foreign key (reported_by_user_id) references public.users;
alter table if exists public.post_reports add constraint FKt97jpb3au0xb2apdsfi3rfbjn foreign key (reviewed_by_user_id) references public.users;
alter table if exists public.post_tags add constraint FK3xvp0906yrfso85ya2w9va83h foreign key (tag_id) references public.tag_types;
alter table if exists public.push_notification_devices add constraint FK7dnkke710cahbc1uix1kwhukl foreign key (user_id) references public.users;
alter table if exists public.recipe_ingredients add constraint FKgukrw6na9f61kb8djkkuvyxy8 foreign key (ingredient_id) references public.ingredients;
alter table if exists public.recipe_ingredients add constraint FK5k17b0cs865rqvok77ut5i68p foreign key (user_meal_post_id) references public.user_meal_posts;
alter table if exists public.recipe_steps add constraint FK1v1velaxvoht4e9ivky0mhev foreign key (meal_id) references public.meals;
alter table if exists public.recipe_steps add constraint FK2wkm0y8xa5jfutw5xd9tv34vu foreign key (user_meal_post_id) references public.user_meal_posts;
alter table if exists public.recipe_tags add constraint FKp4c5gpwklpq6u1qotshwuwf94 foreign key (user_meal_post_id) references public.user_meal_posts;
alter table if exists public.recipe_tags add constraint FKsep8w0iny0y942q9gil36hgco foreign key (tag_id) references public.tag_types;
alter table if exists public.saved_recipes add constraint FKndo5fk5d96a04n1cl5rp1dr4y foreign key (user_meal_post_id) references public.user_meal_posts;
alter table if exists public.saved_recipes add constraint FK1ya4vlv7a3cuvar9e1cc53qfv foreign key (user_id) references public.users;
alter table if exists public.user_auth_providers add constraint FK4vnnbstpq13yo06fl4ynj3rub foreign key (provider_id) references public.auth_providers;
alter table if exists public.user_auth_providers add constraint FK36nn9pmlugyb6c34h3vakuai foreign key (user_id) references public.users;
alter table if exists public.user_meal_posts add constraint FKk7bi5n4qkejkpyldavko9q1fv foreign key (author_user_id) references public.users;
alter table if exists public.user_meal_posts add constraint FK6m142nn822s4di1omo04drta3 foreign key (meal_id) references public.meals;
alter table if exists public.user_nutrient_goals add constraint FKcdi42yi2yauyip5644hdjdb07 foreign key (nutrient_id) references public.nutrients;
alter table if exists public.user_nutrient_goals add constraint FKowc5cp15fee3gbib0i53sl7uq foreign key (user_id) references public.users;
alter table if exists public.user_profiles add constraint FKjcad5nfve11khsnpwj1mv8frj foreign key (user_id) references public.users;
alter table if exists public.user_recipe_ai_checks add constraint FKaph97a35khfd5rgm1hxblphau foreign key (ai_recipe_review_id) references public.ai_recipe_reviews;
alter table if exists public.user_recipe_ai_checks add constraint FKlt1s6w2860s5pq0hu0lx7hca9 foreign key (user_meal_post_id) references public.user_meal_posts;
alter table if exists public.user_recipe_ai_checks add constraint FKbhism74h9q4kafuh7ohr04ykg foreign key (user_id) references public.users;
alter table if exists public.user_settings add constraint FK8v82nj88rmai0nyck19f873dw foreign key (user_id) references public.users;
alter table if exists public.users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references public.roles;
alter table if exists public.verification_codes add constraint FKa4qo6nts1xd94owirq5evcpda foreign key (user_id) references public.users;
alter table if exists public.wellness_profiles add constraint FK2fn1lbaw6ip0aj2r3394du1x4 foreign key (user_id) references public.users;



create view public.community_meal_posts as
select p.user_meal_post_id as post_id,
       p.author_user_id as user_id,
       p.meal_id as tagged_meal_id,
       p.user_meal_post_id,
       p.description as caption,
       'PUBLIC'::varchar(20) as visibility,
       true as allow_comments,
       true as allow_replies,
       case when p.status = 'PUBLISHED' then 'ACTIVE' else 'ARCHIVED' end::varchar(20) as status,
       p.created_at,
       p.updated_at
from public.user_meal_posts p;

