-- Consolidated schema baseline.
-- Contains the original migrations in version order so fresh databases reach the same final schema.
-- Existing databases keep their Flyway history; validation is disabled for this intentional squash.
-- ============================================================================
-- Original migration: V1__initial_schema.sql
-- ============================================================================
-- Clean development baseline generated from the active JPA model.
-- User meal posts are the aggregate root; ingredients and cooking steps are children.
create table public.ai_food_analyses (
    ai_food_analysis_id integer generated by default as identity,
    completion_tokens integer,
    confidence_score numeric(38, 2),
    corrected_serving_size numeric(10, 2),
    database_matched boolean,
    nutrition_fallback_used boolean,
    prompt_tokens integer,
    user_confirmed boolean,
    user_id integer not null,
    created_at timestamp(6) not null,
    feedback_at timestamp(6),
    latency_ms bigint,
    status varchar(20) not null,
    corrected_serving_unit varchar(40),
    prompt_version varchar(50),
    detected_serving_text varchar(100),
    model_name varchar(120),
    corrected_food_name varchar(150),
    detected_food_name varchar(150),
    analysis_text varchar(1000),
    input_text varchar(255) not null,
    primary key (ai_food_analysis_id)
);

create table public.ai_food_analysis_nutrients (
    ai_food_analysis_id integer not null,
    analysis_nutrient_id integer generated by default as identity,
    estimated_amount numeric(38, 2) not null,
    nutrient_id integer not null,
    primary key (analysis_nutrient_id)
);

create table public.ai_food_suggestions (
    ai_food_analysis_id integer not null,
    ai_food_suggestion_id integer generated by default as identity,
    priority integer not null,
    suggestion_type varchar(50) not null,
    title varchar(150) not null,
    description varchar(255) not null,
    reason varchar(255),
    primary key (ai_food_suggestion_id)
);

create table public.ai_recipe_reviews (
    ai_recipe_review_id integer generated by default as identity,
    user_meal_post_id integer not null,
    created_at timestamp(6) not null,
    status varchar(20) not null,
    model_name varchar(100),
    summary varchar(1000),
    feedback varchar(255),
    model_response varchar(255),
    primary key (ai_recipe_review_id)
);

create table public.ai_recommendation_items (
    meal_id integer not null,
    rank_order integer not null,
    recommendation_id integer not null,
    recommendation_item_id integer generated by default as identity,
    created_at timestamp(6) not null,
    reason_text varchar(500),
    primary key (recommendation_item_id)
);

create table public.ai_recommendations (
    mood_id integer,
    recommendation_id integer generated by default as identity,
    user_id integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    status varchar(20) not null,
    request_text varchar(255),
    response_text varchar(255),
    primary key (recommendation_id)
);

create table public.auth_providers (
    is_active boolean not null,
    provider_id integer generated by default as identity,
    provider_name varchar(50) not null unique,
    primary key (provider_id)
);

create table public.comment_likes (
    comment_id integer not null,
    comment_like_id integer generated by default as identity,
    user_id integer not null,
    created_at timestamp(6) not null,
    primary key (comment_like_id)
);

create table public.daily_nutrient_totals (
    consumed_amount numeric(38, 2) not null,
    daily_nutrient_total_id integer generated by default as identity,
    daily_summary_id integer not null,
    goal_amount numeric(38, 2) not null,
    nutrient_id integer not null,
    percentage numeric(38, 2),
    primary key (daily_nutrient_total_id)
);

create table public.daily_wellness_summaries (
    daily_summary_id integer generated by default as identity,
    mood_id integer,
    summary_date date not null,
    user_id integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    balance_status varchar(30),
    ai_insight_text varchar(255),
    primary key (daily_summary_id)
);

create table public.faqs (
    faq_id integer generated by default as identity,
    is_active boolean not null,
    sort_order integer not null,
    updated_at timestamp(6) not null,
    answer varchar(255) not null,
    question varchar(255) not null,
    primary key (faq_id)
);

create table public.follows (
    follow_id integer generated by default as identity,
    follower_user_id integer not null,
    following_user_id integer not null,
    requested_at timestamp(6) not null,
    responded_at timestamp(6),
    status varchar(20) not null,
    primary key (follow_id)
);

create table public.food_nutrition (
    calories numeric(10, 2) not null,
    carbs numeric(10, 2) not null,
    fat numeric(10, 2) not null,
    fiber numeric(10, 2),
    id integer generated by default as identity,
    is_active boolean not null,
    protein numeric(10, 2) not null,
    serving_size numeric(10, 2) not null,
    sodium numeric(10, 2),
    sugar numeric(10, 2) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    serving_unit varchar(40) not null,
    name varchar(150) not null unique,
    aliases TEXT,
    image_url varchar(255),
    primary key (id)
);

create table public.ingredients (
    ingredient_id integer generated by default as identity,
    default_unit varchar(30),
    ingredient_type varchar(50),
    ingredient_name varchar(100) not null unique,
    description varchar(255),
    image_url varchar(255),
    primary key (ingredient_id)
);

create table public.legal_documents (
    is_active boolean not null,
    legal_document_id integer generated by default as identity,
    effective_at timestamp(6) not null,
    document_type varchar(30) not null,
    version varchar(30) not null,
    title varchar(150) not null,
    content varchar(255) not null,
    primary key (legal_document_id)
);

create table public.meal_categories (
    category_id integer generated by default as identity,
    is_active boolean not null,
    sort_order integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    category_name varchar(50) not null unique,
    description varchar(255),
    primary key (category_id)
);

create table public.meal_favorites (
    meal_favorite_id integer generated by default as identity,
    meal_id integer not null,
    user_id integer not null,
    saved_at timestamp(6) not null,
    primary key (meal_favorite_id)
);

create table public.meal_ingredients (
    display_order integer not null,
    ingredient_id integer not null,
    meal_id integer not null,
    meal_ingredient_id integer generated by default as identity,
    quantity numeric(38, 2),
    unit varchar(30),
    preparation_note varchar(150),
    primary key (meal_ingredient_id)
);

create table public.meal_log_nutrients (
    amount numeric(38, 2) not null,
    meal_log_id integer not null,
    meal_log_nutrient_id integer generated by default as identity,
    nutrient_id integer not null,
    primary key (meal_log_nutrient_id)
);

create table public.meal_log_types (
    meal_log_type_id integer generated by default as identity,
    sort_order integer not null,
    meal_log_type_name varchar(50) not null unique,
    primary key (meal_log_type_id)
);

create table public.meal_logs (
    ai_food_analysis_id integer,
    meal_id integer,
    meal_log_id integer generated by default as identity,
    meal_log_type_id integer not null,
    quantity numeric(38, 2) not null,
    serving_size_id integer,
    user_id integer not null,
    created_at timestamp(6) not null,
    logged_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    entry_method varchar(20) not null,
    custom_food_name varchar(150),
    notes varchar(255),
    primary key (meal_log_id)
);

create table public.meal_nutrition (
    amount_per_serving numeric(38, 2) not null,
    meal_id integer not null,
    meal_nutrition_id integer generated by default as identity,
    nutrient_id integer not null,
    primary key (meal_nutrition_id)
);

create table public.meal_tags (
    meal_id integer not null,
    meal_tag_id integer generated by default as identity,
    tag_id integer not null,
    primary key (meal_tag_id)
);

create table public.meals (
    calories_cached numeric(38, 2),
    category_id integer not null,
    cooking_time_minutes integer,
    created_by_user_id integer,
    is_published boolean not null,
    meal_id integer generated by default as identity,
    protein_grams_cached numeric(38, 2),
    servings integer,
    source_user_meal_post_id integer unique,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    approval_source varchar(20) not null,
    difficulty varchar(20),
    source_type varchar(20) not null,
    meal_name varchar(150) not null,
    description varchar(255),
    main_image_url varchar(255),
    primary key (meal_id)
);

create table public.moods (
    is_active boolean not null,
    mood_id integer generated by default as identity,
    emoji_code varchar(30),
    mood_name varchar(100) not null unique,
    primary key (mood_id)
);

create table public.notifications (
    actor_user_id integer,
    is_read boolean not null,
    notification_id integer generated by default as identity,
    reference_id integer,
    user_id integer not null,
    created_at timestamp(6) not null,
    read_at timestamp(6),
    notification_type varchar(50) not null,
    reference_type varchar(50),
    title varchar(150),
    message varchar(500) not null,
    primary key (notification_id)
);

create table public.nutrients (
    display_order integer not null,
    is_active boolean not null,
    is_core boolean not null,
    nutrient_id integer generated by default as identity,
    unit varchar(20) not null,
    nutrient_name varchar(50) not null unique,
    primary key (nutrient_id)
);

create table public.password_reset_tokens (
    reset_token_id integer generated by default as identity,
    user_id integer not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    used_at timestamp(6),
    token_hash varchar(255) not null,
    primary key (reset_token_id)
);

create table public.post_comments (
    comment_id integer generated by default as identity,
    parent_comment_id integer,
    user_id integer not null,
    user_meal_post_id integer not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    status varchar(20) not null,
    comment_text varchar(255) not null,
    primary key (comment_id)
);

create table public.post_favorites (
    post_favorite_id integer generated by default as identity,
    user_id integer not null,
    user_meal_post_id integer not null,
    saved_at timestamp(6) not null,
    primary key (post_favorite_id)
);

create table public.post_likes (
    post_like_id integer generated by default as identity,
    user_id integer not null,
    user_meal_post_id integer not null,
    created_at timestamp(6) not null,
    primary key (post_like_id),
    constraint uk_post_likes_user_post unique (user_id, user_meal_post_id)
);

create table public.post_media (
    display_order integer not null,
    post_media_id integer generated by default as identity,
    user_meal_post_id integer not null,
    media_type varchar(20) not null,
    media_url varchar(255) not null,
    primary key (post_media_id)
);

create table public.post_reports (
    comment_id integer,
    report_id integer generated by default as identity,
    report_reason_id integer not null,
    reported_by_user_id integer not null,
    reviewed_by_user_id integer,
    user_meal_post_id integer not null,
    created_at timestamp(6) not null,
    reviewed_at timestamp(6),
    moderation_action varchar(20),
    status varchar(20) not null,
    target_type varchar(20) not null,
    admin_note varchar(1000),
    primary key (report_id)
);

create table public.post_tags (
    post_tag_id integer generated by default as identity,
    tag_id integer not null,
    user_meal_post_id integer not null,
    primary key (post_tag_id)
);

create table public.push_notification_devices (
    user_id integer not null,
    device_id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    platform varchar(20) not null,
    token varchar(512) not null unique,
    primary key (device_id)
);

create table public.recipe_ingredients (
    amount numeric(10, 2),
    display_order integer not null,
    ingredient_id integer,
    recipe_ingredient_id integer generated by default as identity,
    user_meal_post_id integer not null,
    unit varchar(30),
    ingredient_name varchar(150) not null,
    preparation_note varchar(150),
    primary key (recipe_ingredient_id)
);

create table public.recipe_steps (
    meal_id integer,
    step_id integer generated by default as identity,
    step_number integer not null,
    user_meal_post_id integer,
    step_title varchar(150),
    image_url varchar(255),
    instruction varchar(255) not null,
    primary key (step_id)
);

create table public.recipe_tags (
    recipe_tag_id integer generated by default as identity,
    tag_id integer not null,
    user_meal_post_id integer not null,
    primary key (recipe_tag_id),
    constraint uk_recipe_tags_recipe_tag unique (user_meal_post_id, tag_id)
);

create table public.report_reasons (
    is_active boolean not null,
    report_reason_id integer generated by default as identity,
    reason_name varchar(100) not null unique,
    primary key (report_reason_id)
);

create table public.roles (
    role_id integer generated by default as identity,
    role_name varchar(50) not null unique,
    description varchar(255),
    primary key (role_id)
);

create table public.saved_recipes (
    saved_recipe_id integer generated by default as identity,
    user_id integer not null,
    user_meal_post_id integer not null,
    saved_at timestamp(6) not null,
    primary key (saved_recipe_id),
    constraint uk_saved_recipes_user_recipe unique (user_id, user_meal_post_id)
);

create table public.serving_sizes (
    is_active boolean not null,
    multiplier numeric(38, 2) not null,
    serving_size_id integer generated by default as identity,
    serving_size_name varchar(50) not null unique,
    description varchar(255),
    primary key (serving_size_id)
);

create table public.support_contacts (
    is_active boolean not null,
    sort_order integer not null,
    support_contact_id integer generated by default as identity,
    contact_type varchar(20) not null,
    display_label varchar(100) not null,
    contact_value varchar(150) not null,
    primary key (support_contact_id)
);

create table public.tag_types (
    is_active boolean not null,
    tag_id integer generated by default as identity,
    tag_scope varchar(20) not null,
    tag_name varchar(100) not null unique,
    description varchar(255),
    primary key (tag_id)
);

create table public.user_auth_providers (
    provider_id integer not null,
    user_auth_provider_id integer generated by default as identity,
    user_id integer not null,
    linked_at timestamp(6) not null,
    provider_email varchar(150),
    provider_user_key varchar(255) not null,
    primary key (user_auth_provider_id)
);

create table public.user_meal_posts (
    author_user_id integer not null,
    cooking_time_minutes integer,
    meal_id integer unique,
    servings integer,
    user_meal_post_id integer generated by default as identity,
    created_at timestamp(6) not null,
    published_at timestamp(6),
    updated_at timestamp(6) not null,
    ai_status varchar(20) not null,
    difficulty varchar(20),
    status varchar(20) not null,
    recipe_name varchar(150) not null,
    ai_review_reason varchar(255),
    description varchar(255),
    main_image_url varchar(255),
    primary key (user_meal_post_id)
);

create table public.user_nutrient_goals (
    effective_from date not null,
    effective_to date,
    goal_amount numeric(38, 2) not null,
    is_active boolean not null,
    nutrient_id integer not null,
    user_id integer not null,
    user_nutrient_goal_id integer generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (user_nutrient_goal_id)
);

create table public.user_profiles (
    date_of_birth date,
    user_id integer not null unique,
    user_profile_id integer generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    gender varchar(30),
    phone_number varchar(30),
    membership_type varchar(50),
    full_name varchar(150) not null,
    location_text varchar(150),
    bio varchar(300),
    profile_image_url varchar(255),
    primary key (user_profile_id)
);

create table public.user_recipe_ai_checks (
    ai_recipe_review_id integer,
    user_id integer not null,
    user_meal_post_id integer not null,
    user_recipe_ai_check_id integer generated by default as identity,
    created_at timestamp(6) not null,
    status varchar(20) not null,
    primary key (user_recipe_ai_check_id)
);

create table public.user_settings (
    email_notifications_enabled boolean not null,
    push_notifications_enabled boolean not null,
    user_id integer not null unique,
    user_setting_id integer generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    language_code varchar(10) not null,
    theme varchar(20) not null,
    primary key (user_setting_id)
);

create table public.users (
    is_verified boolean not null,
    pin_length integer,
    role_id integer not null,
    user_id integer generated by default as identity,
    created_at timestamp(6) not null,
    last_login_at timestamp(6),
    updated_at timestamp(6) not null,
    verified_at timestamp(6),
    status varchar(20) not null,
    pin_hash varchar(100),
    email varchar(150) unique,
    password_hash varchar(255),
    primary key (user_id)
);

create table public.verification_codes (
    attempt_count integer not null,
    user_id integer,
    verification_id integer generated by default as identity,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    verified_at timestamp(6),
    delivery_method varchar(20) not null,
    status varchar(20) not null,
    purpose varchar(30) not null,
    destination varchar(150) not null,
    code_hash varchar(255) not null,
    primary key (verification_id)
);

create table public.wellness_profiles (
    age_cached smallint,
    height_cm numeric(38, 2),
    user_id integer not null unique,
    weight_kg numeric(38, 2),
    wellness_profile_id integer generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    activity_level varchar(50),
    primary key (wellness_profile_id)
);

create index public.idx_ai_recipe_reviews_meal_post_created on public.ai_recipe_reviews (user_meal_post_id, created_at);

create index public.idx_ai_recipe_reviews_status on public.ai_recipe_reviews (status);

create index public.idx_daily_wellness_user_date on public.daily_wellness_summaries (user_id, summary_date);

create index public.idx_daily_wellness_mood_id on public.daily_wellness_summaries (mood_id);

create index public.idx_meal_favorites_meal_id on public.meal_favorites (meal_id);

create index public.idx_meal_favorites_user_id on public.meal_favorites (user_id);

create index public.idx_meal_ingredients_meal_id on public.meal_ingredients (meal_id);

create index public.idx_meal_ingredients_ingredient_id on public.meal_ingredients (ingredient_id);

create index public.idx_meal_logs_user_logged_at on public.meal_logs (user_id, logged_at);

create index public.idx_meal_logs_meal_id on public.meal_logs (meal_id);

create index public.idx_meal_logs_serving_size_id on public.meal_logs (serving_size_id);

create index public.idx_meal_tags_meal_id on public.meal_tags (meal_id);

create index public.idx_meal_tags_tag_id on public.meal_tags (tag_id);

create index public.idx_meals_category_id on public.meals (category_id);

create index public.idx_meals_created_by_user_id on public.meals (created_by_user_id);

create index public.idx_meals_updated_at on public.meals (updated_at);

create index public.idx_notifications_user_created_at on public.notifications (user_id, created_at);

create index public.idx_notifications_actor_user_id on public.notifications (actor_user_id);

create index public.idx_post_comments_post_id_created_at on public.post_comments (user_meal_post_id, created_at);

create index public.idx_post_comments_user_id on public.post_comments (user_id);

create index public.idx_post_comments_parent_comment_id on public.post_comments (parent_comment_id);

create index public.idx_recipe_ingredients_meal_post_order on public.recipe_ingredients (user_meal_post_id, display_order);

create index public.idx_recipe_steps_meal_post_id on public.recipe_steps (user_meal_post_id);

create index public.idx_recipe_steps_meal_post_order on public.recipe_steps (user_meal_post_id, step_number);

create index public.idx_recipe_tags_tag_id on public.recipe_tags (tag_id);

create index public.idx_saved_recipes_meal_post_id on public.saved_recipes (user_meal_post_id);

create index public.idx_user_meal_posts_author_user_id on public.user_meal_posts (author_user_id);

create index public.idx_user_meal_posts_status_updated_at on public.user_meal_posts (status, updated_at);

create index public.idx_user_recipe_ai_checks_user_created on public.user_recipe_ai_checks (user_id, created_at);

create index public.idx_user_recipe_ai_checks_meal_post_created on public.user_recipe_ai_checks (user_meal_post_id, created_at);

alter table
    if exists public.ai_food_analyses
add
    constraint FKnomd9q2buwe8g9onsly0a2ykx foreign key (user_id) references public.users;

alter table
    if exists public.ai_food_analysis_nutrients
add
    constraint FKl60itpfg73y6o0do88dul9x9f foreign key (ai_food_analysis_id) references public.ai_food_analyses;

alter table
    if exists public.ai_food_analysis_nutrients
add
    constraint FK9aw8i2ej1dbm1qrn1bcujhvio foreign key (nutrient_id) references public.nutrients;

alter table
    if exists public.ai_food_suggestions
add
    constraint FK8a3qa5ww9y3pkywtquk120vlc foreign key (ai_food_analysis_id) references public.ai_food_analyses;

alter table
    if exists public.ai_recipe_reviews
add
    constraint FKq7y2e8psxltrm1ekylmwgsa8g foreign key (user_meal_post_id) references public.user_meal_posts;

alter table
    if exists public.ai_recommendation_items
add
    constraint FKltlae8gfcmgck8311gxy66bhh foreign key (meal_id) references public.meals;

alter table
    if exists public.ai_recommendation_items
add
    constraint FKguk7vn7bvde21wew6umyo6fe2 foreign key (recommendation_id) references public.ai_recommendations;

alter table
    if exists public.ai_recommendations
add
    constraint FKh8ow7dh1xu8uvu6hghxxmhxp8 foreign key (mood_id) references public.moods;

alter table
    if exists public.ai_recommendations
add
    constraint FKawyie1nntxfgm46oh0tdk91q5 foreign key (user_id) references public.users;

alter table
    if exists public.comment_likes
add
    constraint FK6q90s6gsqjadphkngyf3y0fop foreign key (comment_id) references public.post_comments;

alter table
    if exists public.comment_likes
add
    constraint FK6h3lbneryl5pyb9ykaju7werx foreign key (user_id) references public.users;

alter table
    if exists public.daily_nutrient_totals
add
    constraint FK8s3egdd7n5cpmns6x2w1bctqq foreign key (daily_summary_id) references public.daily_wellness_summaries;

alter table
    if exists public.daily_nutrient_totals
add
    constraint FKfc4v84c4k0leogpai4bykp13p foreign key (nutrient_id) references public.nutrients;

alter table
    if exists public.daily_wellness_summaries
add
    constraint FKoq95w5tx3b70ybbxfps204mmw foreign key (mood_id) references public.moods;

alter table
    if exists public.daily_wellness_summaries
add
    constraint FKev3jxkdbs5i7rv9vnjdh99yyq foreign key (user_id) references public.users;

alter table
    if exists public.follows
add
    constraint FKe53q5i2pk9a4rddeb47cac9rd foreign key (follower_user_id) references public.users;

alter table
    if exists public.follows
add
    constraint FKk1b1yn6h0224kelm91qetqxen foreign key (following_user_id) references public.users;

alter table
    if exists public.meal_favorites
add
    constraint FKtkwo3071wod0wuofbssnrlq6e foreign key (meal_id) references public.meals;

alter table
    if exists public.meal_favorites
add
    constraint FK5jotc7h3f18406y1oq60uonuk foreign key (user_id) references public.users;

alter table
    if exists public.meal_ingredients
add
    constraint FKr6k76rkha8flnalxb1dbvnsvk foreign key (ingredient_id) references public.ingredients;

alter table
    if exists public.meal_ingredients
add
    constraint FKojifbyy4w8xj272rus01j7b7g foreign key (meal_id) references public.meals;

alter table
    if exists public.meal_log_nutrients
add
    constraint FKaphcg9shvoym8xu7hi5bvuwxj foreign key (meal_log_id) references public.meal_logs;

alter table
    if exists public.meal_log_nutrients
add
    constraint FKt57gebdsx66hr63tft0a8get4 foreign key (nutrient_id) references public.nutrients;

alter table
    if exists public.meal_logs
add
    constraint FKmpvp5aa8rllnkspmmby6oox2i foreign key (ai_food_analysis_id) references public.ai_food_analyses;

alter table
    if exists public.meal_logs
add
    constraint FKgg6at6ji0hpj3ir9vlnx2jgpi foreign key (meal_id) references public.meals;

alter table
    if exists public.meal_logs
add
    constraint FKg5gwdhhlemfwin6n2wjhs8bbw foreign key (meal_log_type_id) references public.meal_log_types;

alter table
    if exists public.meal_logs
add
    constraint FK9ts93kgoqj7uyp7htjt3983bv foreign key (serving_size_id) references public.serving_sizes;

alter table
    if exists public.meal_logs
add
    constraint FKp3xr0rnprrvb2yy6bbc3uypk9 foreign key (user_id) references public.users;

alter table
    if exists public.meal_nutrition
add
    constraint FKjuhdpoqbk7qoqtjlbo9u7xem9 foreign key (meal_id) references public.meals;

alter table
    if exists public.meal_nutrition
add
    constraint FKhf28i2x3q4dfty0o9luoc3tlx foreign key (nutrient_id) references public.nutrients;

alter table
    if exists public.meal_tags
add
    constraint FKjro8tb4giftqb8wbcs3ul1g1l foreign key (meal_id) references public.meals;

alter table
    if exists public.meal_tags
add
    constraint FKfp1vs026awk13eiy00i2df2hs foreign key (tag_id) references public.tag_types;

alter table
    if exists public.meals
add
    constraint FKh2pr37nr7dwstqofw1ysefx4r foreign key (category_id) references public.meal_categories;

alter table
    if exists public.meals
add
    constraint FKfxbm0phcsxgfobco1wjo7yjtr foreign key (created_by_user_id) references public.users;

alter table
    if exists public.meals
add
    constraint FKnkb3mpj1cckcx74iogg0ahale foreign key (source_user_meal_post_id) references public.user_meal_posts;

alter table
    if exists public.notifications
add
    constraint FKc8j0u0suv08ytbh1lamjb5n28 foreign key (actor_user_id) references public.users;

alter table
    if exists public.notifications
add
    constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references public.users;

alter table
    if exists public.password_reset_tokens
add
    constraint FKk3ndxg5xp6v7wd4gjyusp15gq foreign key (user_id) references public.users;

alter table
    if exists public.post_comments
add
    constraint FK21q7y8a124im4g0l4aaxn4ol1 foreign key (parent_comment_id) references public.post_comments;

alter table
    if exists public.post_comments
add
    constraint FKsnxoecngu89u3fh4wdrgf0f2g foreign key (user_id) references public.users;

alter table
    if exists public.post_favorites
add
    constraint FKdyw3b7v5xh2sh8b05pkvb52tq foreign key (user_id) references public.users;

alter table
    if exists public.post_likes
add
    constraint FKkgau5n0nlewg6o9lr4yibqgxj foreign key (user_id) references public.users;

alter table
    if exists public.post_reports
add
    constraint FKm5v2ewbmla1wmgaeldmm3yf9g foreign key (comment_id) references public.post_comments;

alter table
    if exists public.post_reports
add
    constraint FKsrrpmnxe84hxejf7nt2d50qjt foreign key (report_reason_id) references public.report_reasons;

alter table
    if exists public.post_reports
add
    constraint FK121f4omxertppr3jhse77e0bw foreign key (reported_by_user_id) references public.users;

alter table
    if exists public.post_reports
add
    constraint FKt97jpb3au0xb2apdsfi3rfbjn foreign key (reviewed_by_user_id) references public.users;

alter table
    if exists public.post_tags
add
    constraint FK3xvp0906yrfso85ya2w9va83h foreign key (tag_id) references public.tag_types;

alter table
    if exists public.push_notification_devices
add
    constraint FK7dnkke710cahbc1uix1kwhukl foreign key (user_id) references public.users;

alter table
    if exists public.recipe_ingredients
add
    constraint FKgukrw6na9f61kb8djkkuvyxy8 foreign key (ingredient_id) references public.ingredients;

alter table
    if exists public.recipe_ingredients
add
    constraint FK5k17b0cs865rqvok77ut5i68p foreign key (user_meal_post_id) references public.user_meal_posts;

alter table
    if exists public.recipe_steps
add
    constraint FK1v1velaxvoht4e9ivky0mhev foreign key (meal_id) references public.meals;

alter table
    if exists public.recipe_steps
add
    constraint FK2wkm0y8xa5jfutw5xd9tv34vu foreign key (user_meal_post_id) references public.user_meal_posts;

alter table
    if exists public.recipe_tags
add
    constraint FKp4c5gpwklpq6u1qotshwuwf94 foreign key (user_meal_post_id) references public.user_meal_posts;

alter table
    if exists public.recipe_tags
add
    constraint FKsep8w0iny0y942q9gil36hgco foreign key (tag_id) references public.tag_types;

alter table
    if exists public.saved_recipes
add
    constraint FKndo5fk5d96a04n1cl5rp1dr4y foreign key (user_meal_post_id) references public.user_meal_posts;

alter table
    if exists public.saved_recipes
add
    constraint FK1ya4vlv7a3cuvar9e1cc53qfv foreign key (user_id) references public.users;

alter table
    if exists public.user_auth_providers
add
    constraint FK4vnnbstpq13yo06fl4ynj3rub foreign key (provider_id) references public.auth_providers;

alter table
    if exists public.user_auth_providers
add
    constraint FK36nn9pmlugyb6c34h3vakuai foreign key (user_id) references public.users;

alter table
    if exists public.user_meal_posts
add
    constraint FKk7bi5n4qkejkpyldavko9q1fv foreign key (author_user_id) references public.users;

alter table
    if exists public.user_meal_posts
add
    constraint FK6m142nn822s4di1omo04drta3 foreign key (meal_id) references public.meals;

alter table
    if exists public.user_nutrient_goals
add
    constraint FKcdi42yi2yauyip5644hdjdb07 foreign key (nutrient_id) references public.nutrients;

alter table
    if exists public.user_nutrient_goals
add
    constraint FKowc5cp15fee3gbib0i53sl7uq foreign key (user_id) references public.users;

alter table
    if exists public.user_profiles
add
    constraint FKjcad5nfve11khsnpwj1mv8frj foreign key (user_id) references public.users;

alter table
    if exists public.user_recipe_ai_checks
add
    constraint FKaph97a35khfd5rgm1hxblphau foreign key (ai_recipe_review_id) references public.ai_recipe_reviews;

alter table
    if exists public.user_recipe_ai_checks
add
    constraint FKlt1s6w2860s5pq0hu0lx7hca9 foreign key (user_meal_post_id) references public.user_meal_posts;

alter table
    if exists public.user_recipe_ai_checks
add
    constraint FKbhism74h9q4kafuh7ohr04ykg foreign key (user_id) references public.users;

alter table
    if exists public.user_settings
add
    constraint FK8v82nj88rmai0nyck19f873dw foreign key (user_id) references public.users;

alter table
    if exists public.users
add
    constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references public.roles;

alter table
    if exists public.verification_codes
add
    constraint FKa4qo6nts1xd94owirq5evcpda foreign key (user_id) references public.users;

alter table
    if exists public.wellness_profiles
add
    constraint FK2fn1lbaw6ip0aj2r3394du1x4 foreign key (user_id) references public.users;

create view public.community_meal_posts as
select
    p.user_meal_post_id as post_id,
    p.author_user_id as user_id,
    p.meal_id as tagged_meal_id,
    p.user_meal_post_id,
    p.description as caption,
    'PUBLIC' :: varchar(20) as visibility,
    true as allow_comments,
    true as allow_replies,
    case
        when p.status = 'PUBLISHED' then 'ACTIVE'
        else 'ARCHIVED'
    end :: varchar(20) as status,
    p.created_at,
    p.updated_at
from
    public.user_meal_posts p;

-- ============================================================================
-- Original migration: V2__recipes_to_user_meal_posts.sql
-- ============================================================================
-- Upgrade databases created from the earlier consolidated baseline. Fresh
-- databases already use user_meal_posts and therefore skip the rename block.
do $ $ begin if to_regclass('public.recipes') is not null then drop view if exists public.community_meal_posts;

alter table
    public.recipes rename to user_meal_posts;

alter table
    public.user_meal_posts rename column recipe_id to user_meal_post_id;

alter table
    public.ai_recipe_reviews rename column recipe_id to user_meal_post_id;

alter table
    public.post_comments rename column recipe_id to user_meal_post_id;

alter table
    public.post_favorites rename column recipe_id to user_meal_post_id;

alter table
    public.post_likes rename column recipe_id to user_meal_post_id;

alter table
    public.post_media rename column recipe_id to user_meal_post_id;

alter table
    public.post_reports rename column recipe_id to user_meal_post_id;

alter table
    public.post_tags rename column recipe_id to user_meal_post_id;

alter table
    public.recipe_ingredients rename column recipe_id to user_meal_post_id;

alter table
    public.recipe_steps rename column recipe_id to user_meal_post_id;

alter table
    public.recipe_tags rename column recipe_id to user_meal_post_id;

alter table
    public.saved_recipes rename column recipe_id to user_meal_post_id;

alter table
    public.user_recipe_ai_checks rename column recipe_id to user_meal_post_id;

alter table
    public.meals rename column source_recipe_id to source_user_meal_post_id;

end if;

end $ $;

create
or replace view public.community_meal_posts as
select
    p.user_meal_post_id as post_id,
    p.author_user_id as user_id,
    p.meal_id as tagged_meal_id,
    p.user_meal_post_id,
    p.description as caption,
    'PUBLIC' :: varchar(20) as visibility,
    true as allow_comments,
    true as allow_replies,
    case
        when p.status = 'PUBLISHED' then 'ACTIVE'
        else 'ARCHIVED'
    end :: varchar(20) as status,
    p.created_at,
    p.updated_at
from
    public.user_meal_posts p;

-- ============================================================================
-- Original migration: V3__add_category_to_user_meal_posts.sql
-- ============================================================================
alter table
    public.user_meal_posts
add
    column if not exists category_id integer;

create index if not exists idx_user_meal_posts_category_id on public.user_meal_posts (category_id);

do $ $ begin if not exists (
    select
        1
    from
        pg_constraint
    where
        conname = 'fk_user_meal_posts_category'
) then
alter table
    public.user_meal_posts
add
    constraint fk_user_meal_posts_category foreign key (category_id) references public.meal_categories;

end if;

end $ $;

-- ============================================================================
-- Original migration: V4__add_shared_source_to_user_meal_posts.sql
-- ============================================================================
alter table
    public.user_meal_posts
add
    column if not exists shared_from_user_meal_post_id integer;

create index if not exists idx_user_meal_posts_shared_source on public.user_meal_posts (shared_from_user_meal_post_id);

do $ $ begin if not exists (
    select
        1
    from
        pg_constraint
    where
        conname = 'fk_user_meal_posts_shared_source'
) then
alter table
    public.user_meal_posts
add
    constraint fk_user_meal_posts_shared_source foreign key (shared_from_user_meal_post_id) references public.user_meal_posts (user_meal_post_id);

end if;

end $ $;

-- ============================================================================
-- Original migration: V5__add_share_count_to_user_meal_posts.sql
-- ============================================================================
alter table
    public.user_meal_posts
add
    column if not exists share_count bigint not null default 0;

-- ============================================================================
-- Original migration: V6__remove_unused_health_tracking_tables.sql
-- ============================================================================
-- These tables backed the removed admin-only Meal Logs and Nutrient Goals modules.
-- Dropping them permanently removes any data they contain.
drop table if exists public.meal_log_nutrients;

drop table if exists public.meal_logs;

drop table if exists public.meal_log_types;

drop table if exists public.user_nutrient_goals;

-- ============================================================================
-- Original migration: V7__drop_removed_health_tracking_tables.sql
-- ============================================================================
-- V6 may already have been recorded before an older application instance
-- recreated these Hibernate-managed tables. Re-run the cleanup as a new
-- migration; Flyway intentionally never executes an applied version twice.
drop table if exists public.meal_log_nutrients;

drop table if exists public.meal_logs;

drop table if exists public.meal_log_types;

drop table if exists public.user_nutrient_goals;

-- ============================================================================
-- Original migration: V8__drop_legacy_tables_without_entities.sql
-- ============================================================================
-- Remove legacy tables that no longer have JPA entity mappings.
-- Child tables are dropped before their parent tables to satisfy foreign keys.
drop table if exists public.message_read_receipts;

drop table if exists public.message_reactions;

drop table if exists public.message_attachments;

drop table if exists public.chat_participants;

drop table if exists public.shares;

drop table if exists public.flags;

drop table if exists public.reviews;

drop table if exists public.messages;

drop table if exists public.chats;

-- ============================================================================
-- Original migration: V9__add_refresh_tokens.sql
-- ============================================================================
create table public.refresh_tokens (
    refresh_token_id bigint generated by default as identity primary key,
    user_id integer not null references public.users(user_id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamp(6) not null,
    created_at timestamp(6) not null,
    revoked_at timestamp(6),
    replaced_by_hash varchar(64)
);

create index idx_refresh_tokens_user_active on public.refresh_tokens(user_id, revoked_at);

create index idx_refresh_tokens_expires_at on public.refresh_tokens(expires_at);

-- ============================================================================
-- Original migration: V10__add_login_otp_requirement.sql
-- ============================================================================
alter table
    public.users
add
    column login_otp_required boolean not null default false;

-- ============================================================================
-- Original migration: V11__add_user_profile_reports.sql
-- ============================================================================
create table public.user_profile_reports (
    profile_report_id integer generated by default as identity,
    reported_user_id integer not null,
    reported_by_user_id integer not null,
    report_reason_id integer not null,
    status varchar(20) not null,
    created_at timestamp(6) not null,
    primary key (profile_report_id),
    constraint fk_profile_reports_reported_user foreign key (reported_user_id) references public.users (user_id),
    constraint fk_profile_reports_reporter foreign key (reported_by_user_id) references public.users (user_id),
    constraint fk_profile_reports_reason foreign key (report_reason_id) references public.report_reasons (report_reason_id)
);

create index idx_profile_reports_status_created on public.user_profile_reports (status, created_at desc);

-- ============================================================================
-- Original migration: V12__fix_post_comments_legacy_post_id.sql
-- ============================================================================
-- Some upgraded databases kept the legacy post_id column after comments were
-- moved to user_meal_posts. Hibernate writes user_meal_post_id, so a remaining
-- NOT NULL post_id makes every new comment fail.
do $ $ begin if exists (
    select
        1
    from
        information_schema.columns
    where
        table_schema = 'public'
        and table_name = 'post_comments'
        and column_name = 'post_id'
) then if exists (
    select
        1
    from
        information_schema.columns
    where
        table_schema = 'public'
        and table_name = 'post_comments'
        and column_name = 'user_meal_post_id'
) then
update
    public.post_comments
set
    user_meal_post_id = post_id
where
    user_meal_post_id is null
    and post_id is not null;

if exists (
    select
        1
    from
        public.post_comments
    where
        user_meal_post_id is null
) then raise exception 'Cannot remove post_comments.post_id: comments without a post still exist';

end if;

alter table
    public.post_comments
alter column
    user_meal_post_id
set
    not null;

alter table
    public.post_comments drop column post_id cascade;

else
alter table
    public.post_comments rename column post_id to user_meal_post_id;

end if;

end if;

end $ $;

create index if not exists idx_post_comments_post_id_created_at on public.post_comments (user_meal_post_id, created_at);

-- ============================================================================
-- Original migration: V13__add_phone_verification_to_user_profiles.sql
-- ============================================================================
alter table
    public.user_profiles
add
    column if not exists is_phone_verified boolean not null default false,
add
    column if not exists phone_verified_at timestamp(6);

-- ============================================================================
-- Original migration: V14__add_phone_number_to_users.sql
-- ============================================================================
alter table
    public.users
add
    column if not exists phone_number varchar(30);

create unique index if not exists uk_users_phone_number on public.users (phone_number)
where
    phone_number is not null;

update
    public.users u
set
    phone_number = up.phone_number
from
    public.user_profiles up
where
    u.user_id = up.user_id
    and u.phone_number is null
    and up.phone_number is not null
    and not exists (
        select
            1
        from
            public.users existing
        where
            existing.phone_number = up.phone_number
    );

-- ============================================================================
-- Original migration: V15__add_user_auth_version.sql
-- ============================================================================
alter table
    public.users
add
    column auth_version integer not null default 0;

alter table
    public.users
add
    constraint ck_users_auth_version_non_negative check (auth_version >= 0);

-- ============================================================================
-- Original migration: V16__add_scraped_meal_sources.sql
-- ============================================================================
-- Preserve original English, optional source Khmer title, ingredient text and
-- nutrition basis for review and future translation without altering the source.
CREATE TABLE scraped_meal_sources (
    meal_id INTEGER PRIMARY KEY REFERENCES meals(meal_id) ON DELETE CASCADE,
    source_url VARCHAR(1000) NOT NULL UNIQUE,
    source_payload TEXT NOT NULL,
    review_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Source documents are backend-only. The migration owner retains access;
-- client roles must not read unpublished recipes through Supabase's Data API.
ALTER TABLE
    scraped_meal_sources ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE scraped_meal_sources
FROM
    PUBLIC;

DO $ $ BEGIN IF EXISTS (
    SELECT
        1
    FROM
        pg_roles
    WHERE
        rolname = 'anon'
) THEN REVOKE ALL ON TABLE scraped_meal_sources
FROM
    anon;

END IF;

IF EXISTS (
    SELECT
        1
    FROM
        pg_roles
    WHERE
        rolname = 'authenticated'
) THEN REVOKE ALL ON TABLE scraped_meal_sources
FROM
    authenticated;

END IF;

END $ $;

-- ============================================================================
-- Original migration: V17__add_profile_report_review_fields.sql
-- ============================================================================
alter table
    public.user_profile_reports
add
    column if not exists moderation_action varchar(20),
add
    column if not exists admin_note varchar(1000),
add
    column if not exists reviewed_by_user_id integer,
add
    column if not exists reviewed_at timestamp(6);

alter table
    public.user_profile_reports drop constraint if exists fk_profile_reports_reviewer;

alter table
    public.user_profile_reports
add
    constraint fk_profile_reports_reviewer foreign key (reviewed_by_user_id) references public.users(user_id);

-- ============================================================================
-- Original migration: V18__report_and_moderation_system.sql
-- ============================================================================
create table public.reports (
    report_id integer generated by default as identity primary key,
    reporter_user_id integer not null references public.users(user_id),
    reported_user_id integer not null references public.users(user_id),
    report_type varchar(20) not null,
    target_id integer not null,
    reason varchar(60) not null,
    description varchar(500),
    content_snapshot varchar(1000),
    status varchar(20) not null default 'PENDING',
    severity varchar(20) not null default 'MEDIUM',
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    reviewed_at timestamp(6),
    reviewed_by integer references public.users(user_id),
    admin_note varchar(1000),
    constraint ck_reports_type check (report_type in ('PROFILE', 'POST', 'COMMENT')),
    constraint ck_reports_status check (
        status in ('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED')
    ),
    constraint ck_reports_severity check (severity in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    constraint ck_reports_not_self check (reporter_user_id <> reported_user_id),
    constraint ck_reports_description_length check (
        description is null
        or char_length(description) <= 500
    )
);

create unique index uq_reports_active_reporter_target on public.reports(reporter_user_id, report_type, target_id)
where
    status in ('PENDING', 'UNDER_REVIEW');

create index idx_reports_review_queue on public.reports(status, severity, created_at);

create index idx_reports_reported_user on public.reports(reported_user_id, created_at desc);

create table public.moderation_actions (
    action_id integer generated by default as identity primary key,
    report_id integer references public.reports(report_id),
    target_user_id integer not null references public.users(user_id),
    admin_user_id integer not null references public.users(user_id),
    action_type varchar(30) not null,
    reason varchar(60) not null,
    admin_note varchar(1000),
    starts_at timestamp(6),
    expires_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    reversed_at timestamp(6),
    reversed_by integer references public.users(user_id),
    constraint ck_moderation_action_type check (
        action_type in (
            'WARNING',
            'CONTENT_HIDDEN',
            'CONTENT_REMOVED',
            'POST_RESTRICTED',
            'COMMENT_RESTRICTED',
            'ACCOUNT_RESTRICTED',
            'SUSPENDED',
            'BANNED'
        )
    ),
    constraint ck_moderation_dates check (
        expires_at is null
        or starts_at is null
        or expires_at > starts_at
    )
);

create index idx_moderation_actions_user on public.moderation_actions(target_user_id, created_at desc);

create table public.moderation_appeals (
    appeal_id integer generated by default as identity primary key,
    moderation_action_id integer not null references public.moderation_actions(action_id),
    user_id integer not null references public.users(user_id),
    reason varchar(500) not null,
    status varchar(20) not null default 'PENDING',
    admin_note varchar(1000),
    created_at timestamp(6) not null default current_timestamp,
    reviewed_at timestamp(6),
    reviewed_by integer references public.users(user_id),
    constraint uq_moderation_appeal_action_user unique (moderation_action_id, user_id),
    constraint ck_appeal_status check (status in ('PENDING', 'APPROVED', 'REJECTED'))
);

create index idx_moderation_appeals_status on public.moderation_appeals(status, created_at);

-- ============================================================================
-- Original migration: V19__add_report_content_snapshot.sql
-- ============================================================================
alter table
    public.reports
add
    column if not exists content_snapshot varchar(1000);

-- ============================================================================
-- Original migration: V20__add_report_attachments_and_mobile_statuses.sql
-- ============================================================================
alter table
    public.reports drop constraint if exists ck_reports_status;

alter table
    public.reports
add
    constraint ck_reports_status check (
        status in (
            'PENDING',
            'UNDER_REVIEW',
            'RESOLVED',
            'NO_VIOLATION',
            'REJECTED',
            'DISMISSED'
        )
    );

create table public.report_attachments (
    attachment_id integer generated by default as identity primary key,
    report_id integer not null references public.reports(report_id) on delete cascade,
    image_url varchar(1000) not null,
    display_order integer not null,
    constraint ck_report_attachments_order check (
        display_order between 0
        and 4
    ),
    constraint uq_report_attachment_order unique (report_id, display_order)
);

create index idx_report_attachments_report on public.report_attachments(report_id, display_order);

-- ============================================================================
-- Original migration: V21__add_report_admin_message.sql
-- ============================================================================
alter table
    public.reports
add
    column if not exists admin_message varchar(1000);

-- ============================================================================
-- Original migration: V22__add_meal_content_translations.sql
-- ============================================================================
create table if not exists public.meal_translations (
    id integer generated by default as identity primary key,
    meal_id integer not null references public.meals(meal_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    meal_name varchar(150) not null,
    description varchar(1000),
    constraint uk_meal_translations_language unique (meal_id, language_code)
);

create table if not exists public.ingredient_translations (
    id integer generated by default as identity primary key,
    ingredient_id integer not null references public.ingredients(ingredient_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(100) not null,
    description varchar(1000),
    constraint uk_ingredient_translations_language unique (ingredient_id, language_code)
);

create table if not exists public.meal_ingredient_translations (
    id integer generated by default as identity primary key,
    meal_ingredient_id integer not null references public.meal_ingredients(meal_ingredient_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    preparation_note varchar(150),
    constraint uk_meal_ingredient_translations_language unique (meal_ingredient_id, language_code)
);

create table if not exists public.recipe_step_translations (
    id integer generated by default as identity primary key,
    recipe_step_id integer not null references public.recipe_steps(step_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    instruction varchar(4000) not null,
    constraint uk_recipe_step_translations_language unique (recipe_step_id, language_code)
);

create table if not exists public.meal_category_translations (
    id integer generated by default as identity primary key,
    category_id integer not null references public.meal_categories(category_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(50) not null,
    description varchar(1000),
    constraint uk_meal_category_translations_language unique (category_id, language_code)
);

create table if not exists public.tag_translations (
    id integer generated by default as identity primary key,
    tag_id integer not null references public.tag_types(tag_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(100) not null,
    description varchar(1000),
    constraint uk_tag_translations_language unique (tag_id, language_code)
);

create table if not exists public.mood_translations (
    id integer generated by default as identity primary key,
    mood_id integer not null references public.moods(mood_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(100) not null,
    constraint uk_mood_translations_language unique (mood_id, language_code)
);

create table if not exists public.meal_moods (
    meal_mood_id integer generated by default as identity primary key,
    meal_id integer not null references public.meals(meal_id) on delete cascade,
    mood_id integer not null references public.moods(mood_id) on delete cascade,
    constraint uk_meal_moods unique (meal_id, mood_id)
);

create index if not exists idx_meal_translations_language on public.meal_translations(language_code);

create index if not exists idx_ingredient_translations_language on public.ingredient_translations(language_code);

create index if not exists idx_recipe_step_translations_language on public.recipe_step_translations(language_code);

create index if not exists idx_meal_category_translations_language on public.meal_category_translations(language_code);

create index if not exists idx_tag_translations_language on public.tag_translations(language_code);

create index if not exists idx_mood_translations_language on public.mood_translations(language_code);

create index if not exists idx_meal_moods_meal on public.meal_moods(meal_id);

insert into
    public.meal_translations (meal_id, language_code, meal_name, description)
select
    meal_id,
    'en',
    meal_name,
    description
from
    public.meals on conflict (meal_id, language_code) do nothing;

insert into
    public.ingredient_translations (ingredient_id, language_code, name, description)
select
    ingredient_id,
    'en',
    ingredient_name,
    description
from
    public.ingredients on conflict (ingredient_id, language_code) do nothing;

insert into
    public.meal_ingredient_translations (
        meal_ingredient_id,
        language_code,
        preparation_note
    )
select
    meal_ingredient_id,
    'en',
    preparation_note
from
    public.meal_ingredients
where
    preparation_note is not null on conflict (meal_ingredient_id, language_code) do nothing;

insert into
    public.recipe_step_translations (recipe_step_id, language_code, instruction)
select
    step_id,
    'en',
    instruction
from
    public.recipe_steps on conflict (recipe_step_id, language_code) do nothing;

insert into
    public.meal_category_translations (category_id, language_code, name, description)
select
    category_id,
    'en',
    category_name,
    description
from
    public.meal_categories on conflict (category_id, language_code) do nothing;

insert into
    public.tag_translations (tag_id, language_code, name, description)
select
    tag_id,
    'en',
    tag_name,
    description
from
    public.tag_types on conflict (tag_id, language_code) do nothing;

insert into
    public.mood_translations (mood_id, language_code, name)
select
    mood_id,
    'en',
    mood_name
from
    public.moods on conflict (mood_id, language_code) do nothing;

alter table
    public.meal_translations enable row level security;

alter table
    public.ingredient_translations enable row level security;

alter table
    public.meal_ingredient_translations enable row level security;

alter table
    public.recipe_step_translations enable row level security;

alter table
    public.meal_category_translations enable row level security;

alter table
    public.tag_translations enable row level security;

alter table
    public.mood_translations enable row level security;

alter table
    public.meal_moods enable row level security;

revoke all on public.meal_translations,
public.ingredient_translations,
public.meal_ingredient_translations,
public.recipe_step_translations,
public.meal_category_translations,
public.tag_translations,
public.mood_translations,
public.meal_moods
from
    anon,
    authenticated;

-- ============================================================================
-- Original migration: V23__clean_and_reseed_meal_categories.sql
-- ============================================================================
-- Clear references from user_meal_posts and meals
UPDATE
    public.user_meal_posts
SET
    meal_id = NULL,
    category_id = NULL;

UPDATE
    public.meals
SET
    source_user_meal_post_id = NULL;

-- Delete meal related child records
DELETE FROM
    public.scraped_meal_sources;

DELETE FROM
    public.meal_ingredient_translations;

DELETE FROM
    public.meal_ingredients;

DELETE FROM
    public.recipe_step_translations;

DELETE FROM
    public.recipe_steps;

DELETE FROM
    public.meal_nutrition;

DELETE FROM
    public.meal_tags;

DELETE FROM
    public.meal_moods;

DELETE FROM
    public.meal_favorites;

DELETE FROM
    public.ai_recommendation_items;

DELETE FROM
    public.meal_translations;

DELETE FROM
    public.meals;

-- Delete ingredient related records
DELETE FROM
    public.recipe_ingredients;

DELETE FROM
    public.ingredient_translations;

DELETE FROM
    public.ingredients;

-- Delete meal category related records
DELETE FROM
    public.meal_category_translations;

DELETE FROM
    public.meal_categories;

-- Reset sequence generators
SELECT
    setval(
        pg_get_serial_sequence('public.meals', 'meal_id'),
        1,
        false
    );

SELECT
    setval(
        pg_get_serial_sequence('public.ingredients', 'ingredient_id'),
        1,
        false
    );

SELECT
    setval(
        pg_get_serial_sequence('public.meal_categories', 'category_id'),
        1,
        false
    );

-- Reseed standard meal categories
INSERT INTO
    public.meal_categories (
        category_id,
        category_name,
        description,
        sort_order,
        is_active,
        created_at,
        updated_at
    )
VALUES
    (
        1,
        'Breakfast',
        'Morning meals and breakfast dishes',
        1,
        true,
        now(),
        now()
    ),
    (
        2,
        'Lunch',
        'Midday meals and lunch dishes',
        2,
        true,
        now(),
        now()
    ),
    (
        3,
        'Dinner',
        'Evening meals and dinners',
        3,
        true,
        now(),
        now()
    ),
    (
        4,
        'Snacks',
        'Light snacks, finger foods, and bites',
        4,
        true,
        now(),
        now()
    ),
    (
        5,
        'Desserts',
        'Sweet treats and traditional desserts',
        5,
        true,
        now(),
        now()
    ),
    (
        6,
        'Soups',
        'Traditional soups, broths, and stews',
        6,
        true,
        now(),
        now()
    ),
    (
        7,
        'Other',
        'Other miscellaneous dishes',
        7,
        true,
        now(),
        now()
    );

SELECT
    setval(
        pg_get_serial_sequence('public.meal_categories', 'category_id'),
        7,
        true
    );

-- Reseed English category translations
INSERT INTO
    public.meal_category_translations (category_id, language_code, name, description)
VALUES
    (
        1,
        'en',
        'Breakfast',
        'Morning meals and breakfast dishes'
    ),
    (
        2,
        'en',
        'Lunch',
        'Midday meals and lunch dishes'
    ),
    (3, 'en', 'Dinner', 'Evening meals and dinners'),
    (
        4,
        'en',
        'Snacks',
        'Light snacks, finger foods, and bites'
    ),
    (
        5,
        'en',
        'Desserts',
        'Sweet treats and traditional desserts'
    ),
    (
        6,
        'en',
        'Soups',
        'Traditional soups, broths, and stews'
    ),
    (7, 'en', 'Other', 'Other miscellaneous dishes') ON CONFLICT (category_id, language_code) DO
UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

-- Reseed Khmer category translations
INSERT INTO
    public.meal_category_translations (category_id, language_code, name, description)
VALUES
    (1, 'km', 'អាហារពេលព្រឹក', 'អាហារសម្រាប់ពេលព្រឹក'),
    (
        2,
        'km',
        'អាហារពេលថ្ងៃត្រង់',
        'អាហារសម្រាប់ពេលថ្ងៃត្រង់'
    ),
    (3, 'km', 'អាហារពេលល្ងាច', 'អាហារសម្រាប់ពេលល្ងាច'),
    (4, 'km', 'អាហារសម្រន់', 'អាហារសម្រន់ស្រាលៗ'),
    (5, 'km', 'បង្អែម', 'បង្អែម និងរបស់ផ្អែមប្រពៃណី'),
    (6, 'km', 'សម្ល', 'សម្ល និងស៊ុបប្រពៃណី'),
    (7, 'km', 'ផ្សេងៗ', 'មុខម្ហូបផ្សេងៗ') ON CONFLICT (category_id, language_code) DO
UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

-- ============================================================================
-- Original migration: V24__add_escalated_status_and_content_restored_action.sql
-- ============================================================================
alter table
    public.reports drop constraint if exists ck_reports_status;

alter table
    public.reports
add
    constraint ck_reports_status check (
        status in (
            'PENDING',
            'UNDER_REVIEW',
            'ESCALATED',
            'RESOLVED',
            'NO_VIOLATION',
            'REJECTED',
            'DISMISSED'
        )
    );

alter table
    public.moderation_actions drop constraint if exists ck_moderation_action_type;

alter table
    public.moderation_actions
add
    constraint ck_moderation_action_type check (
        action_type in (
            'WARNING',
            'CONTENT_HIDDEN',
            'CONTENT_REMOVED',
            'CONTENT_RESTORED',
            'POST_RESTRICTED',
            'COMMENT_RESTRICTED',
            'ACCOUNT_RESTRICTED',
            'SUSPENDED',
            'BANNED'
        )
    );

drop index if exists public.uq_reports_active_reporter_target;

create unique index uq_reports_active_reporter_target on public.reports(reporter_user_id, report_type, target_id)
where
    status in ('PENDING', 'UNDER_REVIEW', 'ESCALATED');

-- ============================================================================
-- Original migration: V25__seed_mood_translations.sql
-- ============================================================================
-- Ensure English translations are populated for all moods
insert into
    public.mood_translations (mood_id, language_code, name)
select
    mood_id,
    'en',
    mood_name
from
    public.moods on conflict (mood_id, language_code) do
update
set
    name = excluded.name;

-- Seed Khmer translations for standard moods
insert into
    public.mood_translations (mood_id, language_code, name)
select
    m.mood_id,
    'km',
    km.name
from
    public.moods m
    join (
        values
            ('Happy', 'សប្បាយរីករាយ'),
            ('Great', 'អស្ចារ្យ'),
            ('Excited', 'រំភើប'),
            ('Joyful', 'រីករាយ'),
            ('Loved', 'មានក្ដីស្រឡាញ់'),
            ('Calm', 'ស្ងប់ស្ងាត់'),
            ('Relaxed', 'ធូរស្រាល'),
            ('Grateful', 'ដឹងគុណ'),
            ('Motivated', 'មានទឹកចិត្ត'),
            ('Focused', 'ផ្តោតអារម្មណ៍'),
            ('Energized', 'មានថាមពល'),
            ('Hopeful', 'មានក្តីសង្ឃឹម'),
            ('Okay', 'ធម្មតា'),
            ('Proud', 'មានមោទនភាព'),
            ('Playful', 'រួសរាយ'),
            ('Curious', 'ចង់ដឹងចង់ឃើញ'),
            ('Surprised', 'ភ្ញាក់ផ្អើល'),
            ('Confident', 'មានទំនុកចិត្ត'),
            ('Peaceful', 'សុខសាន្ត'),
            ('Relieved', 'ធូរទ្រូង'),
            ('Busy', 'រវល់'),
            ('Tired', 'អស់កម្លាំង'),
            ('Sleepy', 'ងងុយគេង'),
            ('Stressed', 'តានតឹង'),
            ('Anxious', 'ព្រួយបារម្ភ'),
            ('Overwhelmed', 'លើសលប់'),
            ('Confused', 'ច្របូកច្របល់'),
            ('Bored', 'អផ្សុក'),
            ('Sad', 'កើតទុក្ខ'),
            ('Lonely', 'ឯកោ'),
            ('Angry', 'ខឹង'),
            ('Frustrated', 'មួម៉ៅ'),
            ('Disappointed', 'ខកចិត្ត'),
            ('Embarrassed', 'ខ្មាសអៀន'),
            ('Nervous', 'ភ័យ'),
            ('Afraid', 'ខ្លាច'),
            ('Hurt', 'ឈឺចាប់'),
            ('Jealous', 'ច្រណែន'),
            ('Drained', 'អស់កម្លាំងល្ហិតល្ហៃ'),
            ('Restless', 'មិនស្រណុកក្នុងចិត្ត'),
            ('Sick', 'ឈឺ'),
            ('Hungry', 'ឃ្លាន')
    ) as km(mood_name, name) on lower(m.mood_name) = lower(km.mood_name) on conflict (mood_id, language_code) do
update
set
    name = excluded.name;

-- ============================================================================
-- Original migration: V26__fix_post_media_legacy_post_id.sql
-- ============================================================================
-- Upgraded databases can retain the old post_id column alongside
-- user_meal_post_id. New meal-post media writes user_meal_post_id, so the
-- legacy column must no longer be mandatory. Keep it for compatibility with
-- old installations and remove only its obsolete NOT NULL requirement.
do $ $ begin if exists (
    select
        1
    from
        information_schema.columns
    where
        table_schema = 'public'
        and table_name = 'post_media'
        and column_name = 'post_id'
) then if exists (
    select
        1
    from
        information_schema.columns
    where
        table_schema = 'public'
        and table_name = 'post_media'
        and column_name = 'user_meal_post_id'
) then
update
    public.post_media
set
    user_meal_post_id = post_id
where
    user_meal_post_id is null
    and post_id is not null;

alter table
    public.post_media
alter column
    post_id drop not null;

else
alter table
    public.post_media rename column post_id to user_meal_post_id;

end if;

end if;

end $ $;

create index if not exists idx_post_media_meal_post_order on public.post_media (user_meal_post_id, display_order);

-- ============================================================================
-- Original migration: V27__add_friend_requests.sql
-- ============================================================================
create table public.friend_requests (
    friend_request_id integer generated by default as identity primary key,
    sender_user_id integer not null references public.users(user_id),
    receiver_user_id integer not null references public.users(user_id),
    status varchar(20) not null,
    created_at timestamp(6) not null,
    responded_at timestamp(6),
    constraint ck_friend_requests_not_self check (sender_user_id <> receiver_user_id),
    constraint ck_friend_requests_status check (status in ('PENDING', 'ACCEPTED', 'DECLINED'))
);

create index idx_friend_requests_sender on public.friend_requests (sender_user_id, created_at desc);

create index idx_friend_requests_receiver on public.friend_requests (receiver_user_id, created_at desc);

-- Only one direction may be pending for a pair. LEAST/GREATEST also closes the
-- reciprocal-request race at the database boundary.
create unique index uq_friend_requests_pending_pair on public.friend_requests (
    least(sender_user_id, receiver_user_id),
    greatest(sender_user_id, receiver_user_id)
)
where
    status = 'PENDING';

-- A request row can produce at most one request notification.
create unique index uq_notifications_friend_request on public.notifications (user_id, reference_id)
where
    notification_type = 'COMMUNITY'
    and reference_type = 'FRIEND_REQUEST';

-- ============================================================================
-- Original migration: V28__enable_friend_requests_rls.sql
-- ============================================================================
-- Friend requests are managed by the Spring API. Do not expose them through
-- Supabase's Data API to anon or authenticated clients.
alter table
    public.friend_requests enable row level security;

-- ============================================================================
-- Original migration: V29__move_friend_requests_into_follows.sql
-- ============================================================================
-- Keep V27/V28 immutable: copy each request event into follows before removing
-- the old table. Ordinary ACTIVE/BLOCKED follows remain untouched.
alter table
    public.follows
add
    column legacy_friend_request_id integer;

insert into
    public.follows (
        follower_user_id,
        following_user_id,
        requested_at,
        responded_at,
        status,
        legacy_friend_request_id
    )
select
    sender_user_id,
    receiver_user_id,
    created_at,
    responded_at,
    case
        status
        when 'PENDING' then 'FRIEND_PENDING'
        when 'ACCEPTED' then 'FRIEND_ACCEPTED'
        when 'DECLINED' then 'FRIEND_DECLINED'
    end,
    friend_request_id
from
    public.friend_requests;

-- Notification reference IDs now point to the migrated follows rows. Drop the
-- partial unique index during remapping to avoid transient ID-swap conflicts.
drop index if exists public.uq_notifications_friend_request;

update
    public.notifications notification
set
    reference_id = follow.follow_id
from
    public.follows follow
where
    follow.legacy_friend_request_id = notification.reference_id
    and notification.reference_type in ('FRIEND_REQUEST', 'FRIEND_REQUEST_ACCEPTED');

create unique index uq_notifications_friend_request on public.notifications (user_id, reference_id)
where
    notification_type = 'COMMUNITY'
    and reference_type = 'FRIEND_REQUEST';

alter table
    public.follows drop column legacy_friend_request_id;

-- Only one pending friend request may exist per unordered user pair, including
-- concurrent reciprocal requests. This does not restrict ordinary follows.
create unique index uq_follows_friend_pending_pair on public.follows (
    least(follower_user_id, following_user_id),
    greatest(follower_user_id, following_user_id)
)
where
    status = 'FRIEND_PENDING';

-- Friend-request events are accessed through the authenticated Spring API.
-- Deny direct Supabase Data API row access unless explicit policies are added.
alter table
    public.follows enable row level security;

drop table public.friend_requests;

-- ============================================================================
-- Original migration: V30__rename_follow_connection_states.sql
-- ============================================================================
-- V27-V29 may already be applied. Rename the migrated event values in a
-- forward-only migration instead of changing their checksums.
drop index if exists public.uq_follows_friend_pending_pair;

update
    public.follows
set
    status = case
        status
        when 'FRIEND_PENDING' then 'FOLLOW_PENDING'
        when 'FRIEND_ACCEPTED' then 'FOLLOW_ACCEPTED'
        when 'FRIEND_DECLINED' then 'FOLLOW_DECLINED'
    end
where
    status in (
        'FRIEND_PENDING',
        'FRIEND_ACCEPTED',
        'FRIEND_DECLINED'
    );

create unique index uq_follows_pending_connection_pair on public.follows (
    least(follower_user_id, following_user_id),
    greatest(follower_user_id, following_user_id)
)
where
    status = 'FOLLOW_PENDING';

drop index if exists public.uq_notifications_friend_request;

update
    public.notifications
set
    reference_type = case
        reference_type
        when 'FRIEND_REQUEST' then 'FOLLOW_CONNECTION'
        when 'FRIEND_REQUEST_ACCEPTED' then 'FOLLOW_CONNECTION_ACCEPTED'
    end
where
    reference_type in ('FRIEND_REQUEST', 'FRIEND_REQUEST_ACCEPTED');

create unique index uq_notifications_follow_connection on public.notifications (user_id, reference_id)
where
    notification_type = 'COMMUNITY'
    and reference_type = 'FOLLOW_CONNECTION';

-- ============================================================================
-- Original migration: V31__add_meal_planner.sql
-- ============================================================================
create table public.planner_meals (
    planner_meal_id integer generated by default as identity primary key,
    legacy_meal_id integer unique,
    category_id integer not null,
    name_en varchar(150) not null,
    name_km varchar(150),
    category_en varchar(80) not null,
    category_km varchar(80),
    description_en text,
    description_km text,
    image_url varchar(500),
    calories numeric(10, 2) not null default 0,
    protein_grams numeric(10, 2) not null default 0,
    carbs_grams numeric(10, 2) not null default 0,
    fat_grams numeric(10, 2) not null default 0,
    cooking_time_minutes integer,
    ingredients_text text,
    instructions_text text,
    tags_text varchar(500),
    is_active boolean not null default true,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_planner_meals_category foreign key (category_id) references public.meal_categories (category_id),
    constraint ck_planner_meals_nutrition check (
        calories >= 0
        and protein_grams >= 0
        and carbs_grams >= 0
        and fat_grams >= 0
    )
);

create table public.weekly_meal_recommendations (
    recommendation_id integer generated by default as identity primary key,
    planner_meal_id integer not null,
    meal_id integer,
    day_of_week varchar(10) not null,
    meal_slot varchar(20) not null,
    note varchar(255),
    is_active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_weekly_recommendations_planner_meal foreign key (planner_meal_id) references public.planner_meals (planner_meal_id) on delete cascade,
    constraint fk_weekly_recommendations_legacy_meal foreign key (meal_id) references public.meals (meal_id) on delete
    set
        null,
        constraint uk_weekly_planner_meal unique (day_of_week, meal_slot, planner_meal_id),
        constraint ck_weekly_meal_recommendation_day check (
            day_of_week in (
                'ALL',
                'MONDAY',
                'TUESDAY',
                'WEDNESDAY',
                'THURSDAY',
                'FRIDAY',
                'SATURDAY',
                'SUNDAY'
            )
        ),
        constraint ck_weekly_meal_recommendation_slot check (
            meal_slot in ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK')
        )
);

create table public.meal_plans (
    meal_plan_id integer generated by default as identity primary key,
    user_id integer not null,
    planner_meal_id integer not null,
    meal_id integer,
    plan_date date not null,
    meal_type varchar(20) not null,
    servings numeric(6, 2) not null default 1,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_meal_plans_user foreign key (user_id) references public.users (user_id) on delete cascade,
    constraint fk_meal_plans_planner_meal foreign key (planner_meal_id) references public.planner_meals (planner_meal_id),
    constraint fk_meal_plans_legacy_meal foreign key (meal_id) references public.meals (meal_id) on delete
    set
        null,
        constraint uk_meal_plans_user_date_type unique (user_id, plan_date, meal_type),
        constraint ck_meal_plans_type check (
            meal_type in ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK')
        ),
        constraint ck_meal_plans_servings check (
            servings > 0
            and servings <= 20
        )
);

create index idx_planner_meals_category on public.planner_meals (category_id, is_active);

create index idx_weekly_meal_schedule on public.weekly_meal_recommendations (day_of_week, meal_slot, is_active, sort_order);

create index idx_weekly_recommendations_planner_meal on public.weekly_meal_recommendations (planner_meal_id, is_active);

create index idx_meal_plans_user_week on public.meal_plans (user_id, plan_date);

create index idx_meal_plans_planner_meal on public.meal_plans (planner_meal_id);

alter table
    public.planner_meals enable row level security;

alter table
    public.weekly_meal_recommendations enable row level security;

alter table
    public.meal_plans enable row level security;

-- ============================================================================
-- Original migration: V35__use_all_day_meal_recommendations.sql
-- ============================================================================
alter table
    public.weekly_meal_recommendations drop constraint if exists ck_weekly_meal_recommendation_day;

delete from
    public.weekly_meal_recommendations row_to_remove
where
    exists (
        select
            1
        from
            public.weekly_meal_recommendations row_to_keep
        where
            row_to_keep.planner_meal_id = row_to_remove.planner_meal_id
            and row_to_keep.meal_slot = row_to_remove.meal_slot
            and row_to_keep.recommendation_id < row_to_remove.recommendation_id
    );

update
    public.weekly_meal_recommendations
set
    day_of_week = 'ALL',
    updated_at = current_timestamp;

alter table
    public.weekly_meal_recommendations
add
    constraint ck_weekly_meal_recommendation_day check (
        day_of_week in (
            'ALL',
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )
    );

-- ============================================================================
-- Original migration: V36__track_meal_plan_adherence.sql
-- ============================================================================
alter table
    public.meal_plans
add
    column status varchar(20) not null default 'PLANNED',
add
    column completed_at timestamp(6),
add
    column actual_servings numeric(6, 2),
add
    constraint ck_meal_plans_status check (status in ('PLANNED', 'EATEN', 'SKIPPED')),
add
    constraint ck_meal_plans_actual_servings check (
        actual_servings is null
        or (
            actual_servings > 0
            and actual_servings <= 20
        )
    );

create index idx_meal_plans_user_date_status on public.meal_plans (user_id, plan_date, status);
