alter table public.reports drop constraint if exists ck_reports_status;
alter table public.reports add constraint ck_reports_status
    check (status in ('PENDING','UNDER_REVIEW','RESOLVED','NO_VIOLATION','REJECTED','DISMISSED'));

create table public.report_attachments (
    attachment_id integer generated by default as identity primary key,
    report_id integer not null references public.reports(report_id) on delete cascade,
    image_url varchar(1000) not null,
    display_order integer not null,
    constraint ck_report_attachments_order check (display_order between 0 and 4),
    constraint uq_report_attachment_order unique (report_id, display_order)
);
create index idx_report_attachments_report on public.report_attachments(report_id, display_order);
