create table if not exists public.meal_translations (
    id integer generated by default as identity primary key,
    meal_id integer not null references public.meals(meal_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    meal_name varchar(150) not null,
    description varchar(1000),
    constraint uk_meal_translations_language unique (meal_id, language_code)
);

create table if not exists public.ingredient_translations (
    id integer generated by default as identity primary key,
    ingredient_id integer not null references public.ingredients(ingredient_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(100) not null,
    description varchar(1000),
    constraint uk_ingredient_translations_language unique (ingredient_id, language_code)
);

create table if not exists public.meal_ingredient_translations (
    id integer generated by default as identity primary key,
    meal_ingredient_id integer not null references public.meal_ingredients(meal_ingredient_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    preparation_note varchar(150),
    constraint uk_meal_ingredient_translations_language unique (meal_ingredient_id, language_code)
);

create table if not exists public.recipe_step_translations (
    id integer generated by default as identity primary key,
    recipe_step_id integer not null references public.recipe_steps(step_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    instruction varchar(4000) not null,
    constraint uk_recipe_step_translations_language unique (recipe_step_id, language_code)
);

create table if not exists public.meal_category_translations (
    id integer generated by default as identity primary key,
    category_id integer not null references public.meal_categories(category_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(50) not null,
    description varchar(1000),
    constraint uk_meal_category_translations_language unique (category_id, language_code)
);

create table if not exists public.tag_translations (
    id integer generated by default as identity primary key,
    tag_id integer not null references public.tag_types(tag_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(100) not null,
    description varchar(1000),
    constraint uk_tag_translations_language unique (tag_id, language_code)
);

create table if not exists public.mood_translations (
    id integer generated by default as identity primary key,
    mood_id integer not null references public.moods(mood_id) on delete cascade,
    language_code varchar(2) not null check (language_code in ('en', 'km')),
    name varchar(100) not null,
    constraint uk_mood_translations_language unique (mood_id, language_code)
);

create table if not exists public.meal_moods (
    meal_mood_id integer generated by default as identity primary key,
    meal_id integer not null references public.meals(meal_id) on delete cascade,
    mood_id integer not null references public.moods(mood_id) on delete cascade,
    constraint uk_meal_moods unique (meal_id, mood_id)
);

create index if not exists idx_meal_translations_language on public.meal_translations(language_code);
create index if not exists idx_ingredient_translations_language on public.ingredient_translations(language_code);
create index if not exists idx_recipe_step_translations_language on public.recipe_step_translations(language_code);
create index if not exists idx_meal_category_translations_language on public.meal_category_translations(language_code);
create index if not exists idx_tag_translations_language on public.tag_translations(language_code);
create index if not exists idx_mood_translations_language on public.mood_translations(language_code);
create index if not exists idx_meal_moods_meal on public.meal_moods(meal_id);

insert into public.meal_translations (meal_id, language_code, meal_name, description)
select meal_id, 'en', meal_name, description from public.meals
on conflict (meal_id, language_code) do nothing;

insert into public.ingredient_translations (ingredient_id, language_code, name, description)
select ingredient_id, 'en', ingredient_name, description from public.ingredients
on conflict (ingredient_id, language_code) do nothing;

insert into public.meal_ingredient_translations (meal_ingredient_id, language_code, preparation_note)
select meal_ingredient_id, 'en', preparation_note from public.meal_ingredients where preparation_note is not null
on conflict (meal_ingredient_id, language_code) do nothing;

insert into public.recipe_step_translations (recipe_step_id, language_code, instruction)
select step_id, 'en', instruction from public.recipe_steps
on conflict (recipe_step_id, language_code) do nothing;

insert into public.meal_category_translations (category_id, language_code, name, description)
select category_id, 'en', category_name, description from public.meal_categories
on conflict (category_id, language_code) do nothing;

insert into public.tag_translations (tag_id, language_code, name, description)
select tag_id, 'en', tag_name, description from public.tag_types
on conflict (tag_id, language_code) do nothing;

insert into public.mood_translations (mood_id, language_code, name)
select mood_id, 'en', mood_name from public.moods
on conflict (mood_id, language_code) do nothing;

alter table public.meal_translations enable row level security;
alter table public.ingredient_translations enable row level security;
alter table public.meal_ingredient_translations enable row level security;
alter table public.recipe_step_translations enable row level security;
alter table public.meal_category_translations enable row level security;
alter table public.tag_translations enable row level security;
alter table public.mood_translations enable row level security;
alter table public.meal_moods enable row level security;

revoke all on public.meal_translations, public.ingredient_translations,
    public.meal_ingredient_translations, public.recipe_step_translations,
    public.meal_category_translations, public.tag_translations,
    public.mood_translations, public.meal_moods from anon, authenticated;

