create table public.friend_requests (
    friend_request_id integer generated by default as identity primary key,
    sender_user_id integer not null references public.users(user_id),
    receiver_user_id integer not null references public.users(user_id),
    status varchar(20) not null,
    created_at timestamp(6) not null,
    responded_at timestamp(6),
    constraint ck_friend_requests_not_self check (sender_user_id <> receiver_user_id),
    constraint ck_friend_requests_status check (status in ('PENDING', 'ACCEPTED', 'DECLINED'))
);

create index idx_friend_requests_sender on public.friend_requests (sender_user_id, created_at desc);
create index idx_friend_requests_receiver on public.friend_requests (receiver_user_id, created_at desc);

-- Only one direction may be pending for a pair. LEAST/GREATEST also closes the
-- reciprocal-request race at the database boundary.
create unique index uq_friend_requests_pending_pair
    on public.friend_requests (
        least(sender_user_id, receiver_user_id),
        greatest(sender_user_id, receiver_user_id)
    )
    where status = 'PENDING';

-- A request row can produce at most one request notification.
create unique index uq_notifications_friend_request
    on public.notifications (user_id, reference_id)
    where notification_type = 'COMMUNITY' and reference_type = 'FRIEND_REQUEST';
