ALTER TABLE posts ADD COLUMN IF NOT EXISTS title VARCHAR(180);

CREATE TABLE IF NOT EXISTS post_likes (
    post_like_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    post_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (post_like_id),
    CONSTRAINT uk_post_likes_user_post UNIQUE (user_id, post_id),
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE
);

CREATE INDEX idx_post_likes_post_id ON post_likes(post_id);
