create table public.planner_meals (
    planner_meal_id integer generated by default as identity primary key,
    legacy_meal_id integer unique,
    category_id integer not null,
    name_en varchar(150) not null,
    name_km varchar(150),
    category_en varchar(80) not null,
    category_km varchar(80),
    description_en text,
    description_km text,
    image_url varchar(500),
    calories numeric(10,2) not null default 0,
    protein_grams numeric(10,2) not null default 0,
    carbs_grams numeric(10,2) not null default 0,
    fat_grams numeric(10,2) not null default 0,
    cooking_time_minutes integer,
    ingredients_text text,
    instructions_text text,
    tags_text varchar(500),
    is_active boolean not null default true,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_planner_meals_category foreign key (category_id)
        references public.meal_categories (category_id),
    constraint ck_planner_meals_nutrition check (
        calories >= 0 and protein_grams >= 0 and carbs_grams >= 0 and fat_grams >= 0)
);

create table public.weekly_meal_recommendations (
    recommendation_id integer generated by default as identity primary key,
    planner_meal_id integer not null,
    meal_id integer,
    day_of_week varchar(10) not null,
    meal_slot varchar(20) not null,
    note varchar(255),
    is_active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_weekly_recommendations_planner_meal foreign key (planner_meal_id)
        references public.planner_meals (planner_meal_id) on delete cascade,
    constraint fk_weekly_recommendations_legacy_meal foreign key (meal_id)
        references public.meals (meal_id) on delete set null,
    constraint uk_weekly_planner_meal unique (day_of_week, meal_slot, planner_meal_id),
    constraint ck_weekly_meal_recommendation_day check (
        day_of_week in ('ALL','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    constraint ck_weekly_meal_recommendation_slot check (
        meal_slot in ('BREAKFAST','LUNCH','DINNER','SNACK'))
);

create table public.meal_plans (
    meal_plan_id integer generated by default as identity primary key,
    user_id integer not null,
    planner_meal_id integer not null,
    meal_id integer,
    plan_date date not null,
    meal_type varchar(20) not null,
    servings numeric(6,2) not null default 1,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_meal_plans_user foreign key (user_id)
        references public.users (user_id) on delete cascade,
    constraint fk_meal_plans_planner_meal foreign key (planner_meal_id)
        references public.planner_meals (planner_meal_id),
    constraint fk_meal_plans_legacy_meal foreign key (meal_id)
        references public.meals (meal_id) on delete set null,
    constraint uk_meal_plans_user_date_type unique (user_id, plan_date, meal_type),
    constraint ck_meal_plans_type check (
        meal_type in ('BREAKFAST','LUNCH','DINNER','SNACK')),
    constraint ck_meal_plans_servings check (servings > 0 and servings <= 20)
);

create index idx_planner_meals_category
    on public.planner_meals (category_id, is_active);
create index idx_weekly_meal_schedule
    on public.weekly_meal_recommendations (day_of_week, meal_slot, is_active, sort_order);
create index idx_weekly_recommendations_planner_meal
    on public.weekly_meal_recommendations (planner_meal_id, is_active);
create index idx_meal_plans_user_week
    on public.meal_plans (user_id, plan_date);
create index idx_meal_plans_planner_meal
    on public.meal_plans (planner_meal_id);

alter table public.planner_meals enable row level security;
alter table public.weekly_meal_recommendations enable row level security;
alter table public.meal_plans enable row level security;
