CREATE TABLE IF NOT EXISTS comment_likes (
    comment_like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id INTEGER NOT NULL REFERENCES post_comments(comment_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_comment_likes_user_comment
    ON comment_likes(user_id, comment_id);
