-- ============================================================================
-- V2: Recipe Scraping Pipeline Enhancements
-- Adds cooking duration granularity, estimated nutrition tracking,
-- ingredient image review & licensing, and translation QA metadata.
-- ============================================================================

-- 1. Duration & Nutrition tracking on meals
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS prep_time_minutes INTEGER;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS resting_time_minutes INTEGER;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS total_time_minutes INTEGER;
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS is_nutrition_estimated BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. Scraped meal source translation & QA tracking
ALTER TABLE public.scraped_meal_sources ADD COLUMN IF NOT EXISTS translation_status VARCHAR(30) NOT NULL DEFAULT 'PENDING';
ALTER TABLE public.scraped_meal_sources ADD COLUMN IF NOT EXISTS translation_error TEXT;
ALTER TABLE public.scraped_meal_sources ADD COLUMN IF NOT EXISTS translation_hash VARCHAR(64);
ALTER TABLE public.scraped_meal_sources ADD COLUMN IF NOT EXISTS glossary_version VARCHAR(20);
ALTER TABLE public.scraped_meal_sources ADD COLUMN IF NOT EXISTS qa_report TEXT;

-- 3. Ingredient Images with licensing and review status
CREATE TABLE IF NOT EXISTS public.ingredient_images (
    ingredient_image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id INTEGER NOT NULL REFERENCES public.ingredients(ingredient_id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL,
    source_type VARCHAR(50) NOT NULL DEFAULT 'DATABASE',
    license_type VARCHAR(50) NOT NULL DEFAULT 'PROPRIETARY',
    storage_path VARCHAR(500),
    review_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ingredient_images_ingredient_id ON public.ingredient_images(ingredient_id);
CREATE INDEX IF NOT EXISTS idx_ingredient_images_review_status ON public.ingredient_images(review_status);

-- 4. Translation memory for reusable Khmer culinary phrases
CREATE TABLE IF NOT EXISTS public.translation_memory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_text VARCHAR(1000) NOT NULL,
    translated_text VARCHAR(2000) NOT NULL,
    category VARCHAR(50) NOT NULL,
    language_code VARCHAR(2) NOT NULL DEFAULT 'km',
    source_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_translation_memory_hash_lang UNIQUE (source_hash, language_code)
);

CREATE INDEX IF NOT EXISTS idx_translation_memory_hash ON public.translation_memory(source_hash);

