CREATE TABLE IF NOT EXISTS post_tags (
    post_tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL REFERENCES posts(post_id) ON DELETE CASCADE,
    tag_id INT NOT NULL REFERENCES tag_types(tag_id),
    CONSTRAINT uk_post_tags_post_tag UNIQUE (post_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_post_tags_post_id ON post_tags(post_id);
CREATE INDEX IF NOT EXISTS idx_post_tags_tag_id ON post_tags(tag_id);
