create table public.refresh_tokens (
    refresh_token_id bigint generated by default as identity primary key,
    user_id integer not null references public.users(user_id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamp(6) not null,
    created_at timestamp(6) not null,
    revoked_at timestamp(6),
    replaced_by_hash varchar(64)
);

create index idx_refresh_tokens_user_active
    on public.refresh_tokens(user_id, revoked_at);
create index idx_refresh_tokens_expires_at
    on public.refresh_tokens(expires_at);
