package com.nhamhealth.nhamhealth_api.entity;

public enum ReportReasonCode {
  SPAM,
  HARASSMENT,
  IMPERSONATION,
  FALSE_INFORMATION,
  INAPPROPRIATE_PROFILE,
  SCAM_OR_FRAUD,
  INAPPROPRIATE_CONTENT,
  DANGEROUS_HEALTH_INFORMATION,
  MISLEADING_NUTRITION_INFORMATION,
  STOLEN_CONTENT,
  HATE_OR_ABUSIVE_CONTENT,
  OTHER
}
